// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: android_state.proto

package com.google.protos.ipc.invalidation;

public final class AndroidState {
  private AndroidState() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ClientMetadataOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional .com.google.protos.ipc.invalidation.Version version = 1;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.Version version = 1;</code>
     *
     * <pre>
     * The version of this state.
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional .com.google.protos.ipc.invalidation.Version version = 1;</code>
     *
     * <pre>
     * The version of this state.
     * </pre>
     */
    com.google.protos.ipc.invalidation.ClientProtocol.Version getVersion();

    // optional string client_key = 2;
    /**
     * <code>optional string client_key = 2;</code>
     *
     * <pre>
     * A key identifying a specific client on a device.
     * </pre>
     */
    boolean hasClientKey();
    /**
     * <code>optional string client_key = 2;</code>
     *
     * <pre>
     * A key identifying a specific client on a device.
     * </pre>
     */
    java.lang.String getClientKey();
    /**
     * <code>optional string client_key = 2;</code>
     *
     * <pre>
     * A key identifying a specific client on a device.
     * </pre>
     */
    com.google.protobuf.ByteString
        getClientKeyBytes();

    // optional int32 client_type = 3;
    /**
     * <code>optional int32 client_type = 3;</code>
     *
     * <pre>
     * The client type for this client.
     * </pre>
     */
    boolean hasClientType();
    /**
     * <code>optional int32 client_type = 3;</code>
     *
     * <pre>
     * The client type for this client.
     * </pre>
     */
    int getClientType();

    // optional string account_name = 4;
    /**
     * <code>optional string account_name = 4;</code>
     *
     * <pre>
     * The user account name for this client.
     * </pre>
     */
    boolean hasAccountName();
    /**
     * <code>optional string account_name = 4;</code>
     *
     * <pre>
     * The user account name for this client.
     * </pre>
     */
    java.lang.String getAccountName();
    /**
     * <code>optional string account_name = 4;</code>
     *
     * <pre>
     * The user account name for this client.
     * </pre>
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    // optional string account_type = 5;
    /**
     * <code>optional string account_type = 5;</code>
     *
     * <pre>
     * The user account type for this client.
     * </pre>
     */
    boolean hasAccountType();
    /**
     * <code>optional string account_type = 5;</code>
     *
     * <pre>
     * The user account type for this client.
     * </pre>
     */
    java.lang.String getAccountType();
    /**
     * <code>optional string account_type = 5;</code>
     *
     * <pre>
     * The user account type for this client.
     * </pre>
     */
    com.google.protobuf.ByteString
        getAccountTypeBytes();

    // optional string auth_type = 6;
    /**
     * <code>optional string auth_type = 6;</code>
     *
     * <pre>
     * The authentication token type that is used for requests from this client.
     * </pre>
     */
    boolean hasAuthType();
    /**
     * <code>optional string auth_type = 6;</code>
     *
     * <pre>
     * The authentication token type that is used for requests from this client.
     * </pre>
     */
    java.lang.String getAuthType();
    /**
     * <code>optional string auth_type = 6;</code>
     *
     * <pre>
     * The authentication token type that is used for requests from this client.
     * </pre>
     */
    com.google.protobuf.ByteString
        getAuthTypeBytes();

    // optional string listener_pkg = 7;
    /**
     * <code>optional string listener_pkg = 7;</code>
     *
     * <pre>
     * The application package name for the client's event listener.
     * </pre>
     */
    boolean hasListenerPkg();
    /**
     * <code>optional string listener_pkg = 7;</code>
     *
     * <pre>
     * The application package name for the client's event listener.
     * </pre>
     */
    java.lang.String getListenerPkg();
    /**
     * <code>optional string listener_pkg = 7;</code>
     *
     * <pre>
     * The application package name for the client's event listener.
     * </pre>
     */
    com.google.protobuf.ByteString
        getListenerPkgBytes();

    // optional string listener_class = 8;
    /**
     * <code>optional string listener_class = 8;</code>
     *
     * <pre>
     * The class name for the client's event listener.
     * </pre>
     */
    boolean hasListenerClass();
    /**
     * <code>optional string listener_class = 8;</code>
     *
     * <pre>
     * The class name for the client's event listener.
     * </pre>
     */
    java.lang.String getListenerClass();
    /**
     * <code>optional string listener_class = 8;</code>
     *
     * <pre>
     * The class name for the client's event listener.
     * </pre>
     */
    com.google.protobuf.ByteString
        getListenerClassBytes();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.ClientMetadata}
   *
   * <pre>
   * Base metadata for an Android client instance.  All of these values
   * are required and invariant for the life of the client.
   * </pre>
   */
  public static final class ClientMetadata extends
      com.google.protobuf.GeneratedMessageLite
      implements ClientMetadataOrBuilder {
    // Use ClientMetadata.newBuilder() to construct.
    private ClientMetadata(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private ClientMetadata(boolean noInit) {}

    private static final ClientMetadata defaultInstance;
    public static ClientMetadata getDefaultInstance() {
      return defaultInstance;
    }

    public ClientMetadata getDefaultInstanceForType() {
      return defaultInstance;
    }

    private ClientMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protos.ipc.invalidation.ClientProtocol.Version.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = version_.toBuilder();
              }
              version_ = input.readMessage(com.google.protos.ipc.invalidation.ClientProtocol.Version.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(version_);
                version_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              clientKey_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              clientType_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              accountName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              accountType_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              authType_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              listenerPkg_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              listenerClass_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<ClientMetadata> PARSER =
        new com.google.protobuf.AbstractParser<ClientMetadata>() {
      public ClientMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientMetadata(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientMetadata> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.google.protos.ipc.invalidation.Version version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private com.google.protos.ipc.invalidation.ClientProtocol.Version version_;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.Version version = 1;</code>
     *
     * <pre>
     * The version of this state.
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.protos.ipc.invalidation.Version version = 1;</code>
     *
     * <pre>
     * The version of this state.
     * </pre>
     */
    public com.google.protos.ipc.invalidation.ClientProtocol.Version getVersion() {
      return version_;
    }

    // optional string client_key = 2;
    public static final int CLIENT_KEY_FIELD_NUMBER = 2;
    private java.lang.Object clientKey_;
    /**
     * <code>optional string client_key = 2;</code>
     *
     * <pre>
     * A key identifying a specific client on a device.
     * </pre>
     */
    public boolean hasClientKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string client_key = 2;</code>
     *
     * <pre>
     * A key identifying a specific client on a device.
     * </pre>
     */
    public java.lang.String getClientKey() {
      java.lang.Object ref = clientKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string client_key = 2;</code>
     *
     * <pre>
     * A key identifying a specific client on a device.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClientKeyBytes() {
      java.lang.Object ref = clientKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 client_type = 3;
    public static final int CLIENT_TYPE_FIELD_NUMBER = 3;
    private int clientType_;
    /**
     * <code>optional int32 client_type = 3;</code>
     *
     * <pre>
     * The client type for this client.
     * </pre>
     */
    public boolean hasClientType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 client_type = 3;</code>
     *
     * <pre>
     * The client type for this client.
     * </pre>
     */
    public int getClientType() {
      return clientType_;
    }

    // optional string account_name = 4;
    public static final int ACCOUNT_NAME_FIELD_NUMBER = 4;
    private java.lang.Object accountName_;
    /**
     * <code>optional string account_name = 4;</code>
     *
     * <pre>
     * The user account name for this client.
     * </pre>
     */
    public boolean hasAccountName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string account_name = 4;</code>
     *
     * <pre>
     * The user account name for this client.
     * </pre>
     */
    public java.lang.String getAccountName() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accountName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string account_name = 4;</code>
     *
     * <pre>
     * The user account name for this client.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string account_type = 5;
    public static final int ACCOUNT_TYPE_FIELD_NUMBER = 5;
    private java.lang.Object accountType_;
    /**
     * <code>optional string account_type = 5;</code>
     *
     * <pre>
     * The user account type for this client.
     * </pre>
     */
    public boolean hasAccountType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string account_type = 5;</code>
     *
     * <pre>
     * The user account type for this client.
     * </pre>
     */
    public java.lang.String getAccountType() {
      java.lang.Object ref = accountType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accountType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string account_type = 5;</code>
     *
     * <pre>
     * The user account type for this client.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAccountTypeBytes() {
      java.lang.Object ref = accountType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string auth_type = 6;
    public static final int AUTH_TYPE_FIELD_NUMBER = 6;
    private java.lang.Object authType_;
    /**
     * <code>optional string auth_type = 6;</code>
     *
     * <pre>
     * The authentication token type that is used for requests from this client.
     * </pre>
     */
    public boolean hasAuthType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string auth_type = 6;</code>
     *
     * <pre>
     * The authentication token type that is used for requests from this client.
     * </pre>
     */
    public java.lang.String getAuthType() {
      java.lang.Object ref = authType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          authType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string auth_type = 6;</code>
     *
     * <pre>
     * The authentication token type that is used for requests from this client.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAuthTypeBytes() {
      java.lang.Object ref = authType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string listener_pkg = 7;
    public static final int LISTENER_PKG_FIELD_NUMBER = 7;
    private java.lang.Object listenerPkg_;
    /**
     * <code>optional string listener_pkg = 7;</code>
     *
     * <pre>
     * The application package name for the client's event listener.
     * </pre>
     */
    public boolean hasListenerPkg() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string listener_pkg = 7;</code>
     *
     * <pre>
     * The application package name for the client's event listener.
     * </pre>
     */
    public java.lang.String getListenerPkg() {
      java.lang.Object ref = listenerPkg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          listenerPkg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string listener_pkg = 7;</code>
     *
     * <pre>
     * The application package name for the client's event listener.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getListenerPkgBytes() {
      java.lang.Object ref = listenerPkg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        listenerPkg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string listener_class = 8;
    public static final int LISTENER_CLASS_FIELD_NUMBER = 8;
    private java.lang.Object listenerClass_;
    /**
     * <code>optional string listener_class = 8;</code>
     *
     * <pre>
     * The class name for the client's event listener.
     * </pre>
     */
    public boolean hasListenerClass() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string listener_class = 8;</code>
     *
     * <pre>
     * The class name for the client's event listener.
     * </pre>
     */
    public java.lang.String getListenerClass() {
      java.lang.Object ref = listenerClass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          listenerClass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string listener_class = 8;</code>
     *
     * <pre>
     * The class name for the client's event listener.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getListenerClassBytes() {
      java.lang.Object ref = listenerClass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        listenerClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance();
      clientKey_ = "";
      clientType_ = 0;
      accountName_ = "";
      accountType_ = "";
      authType_ = "";
      listenerPkg_ = "";
      listenerClass_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClientKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, clientType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAccountNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getAccountTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getAuthTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getListenerPkgBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getListenerClassBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClientKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, clientType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAccountNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getAccountTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getAuthTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getListenerPkgBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getListenerClassBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.AndroidState.ClientMetadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.ClientMetadata}
     *
     * <pre>
     * Base metadata for an Android client instance.  All of these values
     * are required and invariant for the life of the client.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.AndroidState.ClientMetadata, Builder>
        implements com.google.protos.ipc.invalidation.AndroidState.ClientMetadataOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        clientKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        clientType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        accountName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        accountType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        authType_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        listenerPkg_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        listenerClass_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.AndroidState.ClientMetadata getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.AndroidState.ClientMetadata build() {
        com.google.protos.ipc.invalidation.AndroidState.ClientMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.AndroidState.ClientMetadata buildPartial() {
        com.google.protos.ipc.invalidation.AndroidState.ClientMetadata result = new com.google.protos.ipc.invalidation.AndroidState.ClientMetadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientKey_ = clientKey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clientType_ = clientType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.accountName_ = accountName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.accountType_ = accountType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.authType_ = authType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.listenerPkg_ = listenerPkg_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.listenerClass_ = listenerClass_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.AndroidState.ClientMetadata other) {
        if (other == com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          mergeVersion(other.getVersion());
        }
        if (other.hasClientKey()) {
          bitField0_ |= 0x00000002;
          clientKey_ = other.clientKey_;
          
        }
        if (other.hasClientType()) {
          setClientType(other.getClientType());
        }
        if (other.hasAccountName()) {
          bitField0_ |= 0x00000008;
          accountName_ = other.accountName_;
          
        }
        if (other.hasAccountType()) {
          bitField0_ |= 0x00000010;
          accountType_ = other.accountType_;
          
        }
        if (other.hasAuthType()) {
          bitField0_ |= 0x00000020;
          authType_ = other.authType_;
          
        }
        if (other.hasListenerPkg()) {
          bitField0_ |= 0x00000040;
          listenerPkg_ = other.listenerPkg_;
          
        }
        if (other.hasListenerClass()) {
          bitField0_ |= 0x00000080;
          listenerClass_ = other.listenerClass_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.AndroidState.ClientMetadata) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.google.protos.ipc.invalidation.Version version = 1;
      private com.google.protos.ipc.invalidation.ClientProtocol.Version version_ = com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance();
      /**
       * <code>optional .com.google.protos.ipc.invalidation.Version version = 1;</code>
       *
       * <pre>
       * The version of this state.
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.Version version = 1;</code>
       *
       * <pre>
       * The version of this state.
       * </pre>
       */
      public com.google.protos.ipc.invalidation.ClientProtocol.Version getVersion() {
        return version_;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.Version version = 1;</code>
       *
       * <pre>
       * The version of this state.
       * </pre>
       */
      public Builder setVersion(com.google.protos.ipc.invalidation.ClientProtocol.Version value) {
        if (value == null) {
          throw new NullPointerException();
        }
        version_ = value;

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.Version version = 1;</code>
       *
       * <pre>
       * The version of this state.
       * </pre>
       */
      public Builder setVersion(
          com.google.protos.ipc.invalidation.ClientProtocol.Version.Builder builderForValue) {
        version_ = builderForValue.build();

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.Version version = 1;</code>
       *
       * <pre>
       * The version of this state.
       * </pre>
       */
      public Builder mergeVersion(com.google.protos.ipc.invalidation.ClientProtocol.Version value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            version_ != com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance()) {
          version_ =
            com.google.protos.ipc.invalidation.ClientProtocol.Version.newBuilder(version_).mergeFrom(value).buildPartial();
        } else {
          version_ = value;
        }

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.Version version = 1;</code>
       *
       * <pre>
       * The version of this state.
       * </pre>
       */
      public Builder clearVersion() {
        version_ = com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      // optional string client_key = 2;
      private java.lang.Object clientKey_ = "";
      /**
       * <code>optional string client_key = 2;</code>
       *
       * <pre>
       * A key identifying a specific client on a device.
       * </pre>
       */
      public boolean hasClientKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string client_key = 2;</code>
       *
       * <pre>
       * A key identifying a specific client on a device.
       * </pre>
       */
      public java.lang.String getClientKey() {
        java.lang.Object ref = clientKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clientKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string client_key = 2;</code>
       *
       * <pre>
       * A key identifying a specific client on a device.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClientKeyBytes() {
        java.lang.Object ref = clientKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string client_key = 2;</code>
       *
       * <pre>
       * A key identifying a specific client on a device.
       * </pre>
       */
      public Builder setClientKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientKey_ = value;
        
        return this;
      }
      /**
       * <code>optional string client_key = 2;</code>
       *
       * <pre>
       * A key identifying a specific client on a device.
       * </pre>
       */
      public Builder clearClientKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientKey_ = getDefaultInstance().getClientKey();
        
        return this;
      }
      /**
       * <code>optional string client_key = 2;</code>
       *
       * <pre>
       * A key identifying a specific client on a device.
       * </pre>
       */
      public Builder setClientKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientKey_ = value;
        
        return this;
      }

      // optional int32 client_type = 3;
      private int clientType_ ;
      /**
       * <code>optional int32 client_type = 3;</code>
       *
       * <pre>
       * The client type for this client.
       * </pre>
       */
      public boolean hasClientType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 client_type = 3;</code>
       *
       * <pre>
       * The client type for this client.
       * </pre>
       */
      public int getClientType() {
        return clientType_;
      }
      /**
       * <code>optional int32 client_type = 3;</code>
       *
       * <pre>
       * The client type for this client.
       * </pre>
       */
      public Builder setClientType(int value) {
        bitField0_ |= 0x00000004;
        clientType_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 client_type = 3;</code>
       *
       * <pre>
       * The client type for this client.
       * </pre>
       */
      public Builder clearClientType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientType_ = 0;
        
        return this;
      }

      // optional string account_name = 4;
      private java.lang.Object accountName_ = "";
      /**
       * <code>optional string account_name = 4;</code>
       *
       * <pre>
       * The user account name for this client.
       * </pre>
       */
      public boolean hasAccountName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string account_name = 4;</code>
       *
       * <pre>
       * The user account name for this client.
       * </pre>
       */
      public java.lang.String getAccountName() {
        java.lang.Object ref = accountName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accountName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string account_name = 4;</code>
       *
       * <pre>
       * The user account name for this client.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        java.lang.Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account_name = 4;</code>
       *
       * <pre>
       * The user account name for this client.
       * </pre>
       */
      public Builder setAccountName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        accountName_ = value;
        
        return this;
      }
      /**
       * <code>optional string account_name = 4;</code>
       *
       * <pre>
       * The user account name for this client.
       * </pre>
       */
      public Builder clearAccountName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        accountName_ = getDefaultInstance().getAccountName();
        
        return this;
      }
      /**
       * <code>optional string account_name = 4;</code>
       *
       * <pre>
       * The user account name for this client.
       * </pre>
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        accountName_ = value;
        
        return this;
      }

      // optional string account_type = 5;
      private java.lang.Object accountType_ = "";
      /**
       * <code>optional string account_type = 5;</code>
       *
       * <pre>
       * The user account type for this client.
       * </pre>
       */
      public boolean hasAccountType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string account_type = 5;</code>
       *
       * <pre>
       * The user account type for this client.
       * </pre>
       */
      public java.lang.String getAccountType() {
        java.lang.Object ref = accountType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accountType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string account_type = 5;</code>
       *
       * <pre>
       * The user account type for this client.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAccountTypeBytes() {
        java.lang.Object ref = accountType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account_type = 5;</code>
       *
       * <pre>
       * The user account type for this client.
       * </pre>
       */
      public Builder setAccountType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        accountType_ = value;
        
        return this;
      }
      /**
       * <code>optional string account_type = 5;</code>
       *
       * <pre>
       * The user account type for this client.
       * </pre>
       */
      public Builder clearAccountType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        accountType_ = getDefaultInstance().getAccountType();
        
        return this;
      }
      /**
       * <code>optional string account_type = 5;</code>
       *
       * <pre>
       * The user account type for this client.
       * </pre>
       */
      public Builder setAccountTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        accountType_ = value;
        
        return this;
      }

      // optional string auth_type = 6;
      private java.lang.Object authType_ = "";
      /**
       * <code>optional string auth_type = 6;</code>
       *
       * <pre>
       * The authentication token type that is used for requests from this client.
       * </pre>
       */
      public boolean hasAuthType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string auth_type = 6;</code>
       *
       * <pre>
       * The authentication token type that is used for requests from this client.
       * </pre>
       */
      public java.lang.String getAuthType() {
        java.lang.Object ref = authType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          authType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string auth_type = 6;</code>
       *
       * <pre>
       * The authentication token type that is used for requests from this client.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAuthTypeBytes() {
        java.lang.Object ref = authType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string auth_type = 6;</code>
       *
       * <pre>
       * The authentication token type that is used for requests from this client.
       * </pre>
       */
      public Builder setAuthType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        authType_ = value;
        
        return this;
      }
      /**
       * <code>optional string auth_type = 6;</code>
       *
       * <pre>
       * The authentication token type that is used for requests from this client.
       * </pre>
       */
      public Builder clearAuthType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        authType_ = getDefaultInstance().getAuthType();
        
        return this;
      }
      /**
       * <code>optional string auth_type = 6;</code>
       *
       * <pre>
       * The authentication token type that is used for requests from this client.
       * </pre>
       */
      public Builder setAuthTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        authType_ = value;
        
        return this;
      }

      // optional string listener_pkg = 7;
      private java.lang.Object listenerPkg_ = "";
      /**
       * <code>optional string listener_pkg = 7;</code>
       *
       * <pre>
       * The application package name for the client's event listener.
       * </pre>
       */
      public boolean hasListenerPkg() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string listener_pkg = 7;</code>
       *
       * <pre>
       * The application package name for the client's event listener.
       * </pre>
       */
      public java.lang.String getListenerPkg() {
        java.lang.Object ref = listenerPkg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          listenerPkg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string listener_pkg = 7;</code>
       *
       * <pre>
       * The application package name for the client's event listener.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getListenerPkgBytes() {
        java.lang.Object ref = listenerPkg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          listenerPkg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string listener_pkg = 7;</code>
       *
       * <pre>
       * The application package name for the client's event listener.
       * </pre>
       */
      public Builder setListenerPkg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        listenerPkg_ = value;
        
        return this;
      }
      /**
       * <code>optional string listener_pkg = 7;</code>
       *
       * <pre>
       * The application package name for the client's event listener.
       * </pre>
       */
      public Builder clearListenerPkg() {
        bitField0_ = (bitField0_ & ~0x00000040);
        listenerPkg_ = getDefaultInstance().getListenerPkg();
        
        return this;
      }
      /**
       * <code>optional string listener_pkg = 7;</code>
       *
       * <pre>
       * The application package name for the client's event listener.
       * </pre>
       */
      public Builder setListenerPkgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        listenerPkg_ = value;
        
        return this;
      }

      // optional string listener_class = 8;
      private java.lang.Object listenerClass_ = "";
      /**
       * <code>optional string listener_class = 8;</code>
       *
       * <pre>
       * The class name for the client's event listener.
       * </pre>
       */
      public boolean hasListenerClass() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string listener_class = 8;</code>
       *
       * <pre>
       * The class name for the client's event listener.
       * </pre>
       */
      public java.lang.String getListenerClass() {
        java.lang.Object ref = listenerClass_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          listenerClass_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string listener_class = 8;</code>
       *
       * <pre>
       * The class name for the client's event listener.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getListenerClassBytes() {
        java.lang.Object ref = listenerClass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          listenerClass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string listener_class = 8;</code>
       *
       * <pre>
       * The class name for the client's event listener.
       * </pre>
       */
      public Builder setListenerClass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        listenerClass_ = value;
        
        return this;
      }
      /**
       * <code>optional string listener_class = 8;</code>
       *
       * <pre>
       * The class name for the client's event listener.
       * </pre>
       */
      public Builder clearListenerClass() {
        bitField0_ = (bitField0_ & ~0x00000080);
        listenerClass_ = getDefaultInstance().getListenerClass();
        
        return this;
      }
      /**
       * <code>optional string listener_class = 8;</code>
       *
       * <pre>
       * The class name for the client's event listener.
       * </pre>
       */
      public Builder setListenerClassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        listenerClass_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.ClientMetadata)
    }

    static {
      defaultInstance = new ClientMetadata(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.ClientMetadata)
  }

  public interface ClientPropertyOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional string key = 1;
    /**
     * <code>optional string key = 1;</code>
     *
     * <pre>
     * The key of the stored property
     * </pre>
     */
    boolean hasKey();
    /**
     * <code>optional string key = 1;</code>
     *
     * <pre>
     * The key of the stored property
     * </pre>
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 1;</code>
     *
     * <pre>
     * The key of the stored property
     * </pre>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // optional bytes value = 2;
    /**
     * <code>optional bytes value = 2;</code>
     *
     * <pre>
     * The value of the stored property
     * </pre>
     */
    boolean hasValue();
    /**
     * <code>optional bytes value = 2;</code>
     *
     * <pre>
     * The value of the stored property
     * </pre>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.ClientProperty}
   *
   * <pre>
   * Internal properties associated with the client by the client library.  These
   * properties may change or grow over time.
   * </pre>
   */
  public static final class ClientProperty extends
      com.google.protobuf.GeneratedMessageLite
      implements ClientPropertyOrBuilder {
    // Use ClientProperty.newBuilder() to construct.
    private ClientProperty(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private ClientProperty(boolean noInit) {}

    private static final ClientProperty defaultInstance;
    public static ClientProperty getDefaultInstance() {
      return defaultInstance;
    }

    public ClientProperty getDefaultInstanceForType() {
      return defaultInstance;
    }

    private ClientProperty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<ClientProperty> PARSER =
        new com.google.protobuf.AbstractParser<ClientProperty>() {
      public ClientProperty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientProperty(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientProperty> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>optional string key = 1;</code>
     *
     * <pre>
     * The key of the stored property
     * </pre>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string key = 1;</code>
     *
     * <pre>
     * The key of the stored property
     * </pre>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 1;</code>
     *
     * <pre>
     * The key of the stored property
     * </pre>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>optional bytes value = 2;</code>
     *
     * <pre>
     * The value of the stored property
     * </pre>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes value = 2;</code>
     *
     * <pre>
     * The value of the stored property
     * </pre>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private void initFields() {
      key_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, value_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.AndroidState.ClientProperty prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.ClientProperty}
     *
     * <pre>
     * Internal properties associated with the client by the client library.  These
     * properties may change or grow over time.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.AndroidState.ClientProperty, Builder>
        implements com.google.protos.ipc.invalidation.AndroidState.ClientPropertyOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.AndroidState.ClientProperty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.AndroidState.ClientProperty getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.AndroidState.ClientProperty.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.AndroidState.ClientProperty build() {
        com.google.protos.ipc.invalidation.AndroidState.ClientProperty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.AndroidState.ClientProperty buildPartial() {
        com.google.protos.ipc.invalidation.AndroidState.ClientProperty result = new com.google.protos.ipc.invalidation.AndroidState.ClientProperty(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.AndroidState.ClientProperty other) {
        if (other == com.google.protos.ipc.invalidation.AndroidState.ClientProperty.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.AndroidState.ClientProperty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.AndroidState.ClientProperty) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string key = 1;
      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 1;</code>
       *
       * <pre>
       * The key of the stored property
       * </pre>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string key = 1;</code>
       *
       * <pre>
       * The key of the stored property
       * </pre>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       *
       * <pre>
       * The key of the stored property
       * </pre>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       *
       * <pre>
       * The key of the stored property
       * </pre>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       *
       * <pre>
       * The key of the stored property
       * </pre>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       *
       * <pre>
       * The key of the stored property
       * </pre>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        
        return this;
      }

      // optional bytes value = 2;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes value = 2;</code>
       *
       * <pre>
       * The value of the stored property
       * </pre>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes value = 2;</code>
       *
       * <pre>
       * The value of the stored property
       * </pre>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>optional bytes value = 2;</code>
       *
       * <pre>
       * The value of the stored property
       * </pre>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes value = 2;</code>
       *
       * <pre>
       * The value of the stored property
       * </pre>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.ClientProperty)
    }

    static {
      defaultInstance = new ClientProperty(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.ClientProperty)
  }

  public interface StoredStateOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;</code>
     */
    boolean hasMetadata();
    /**
     * <code>optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;</code>
     */
    com.google.protos.ipc.invalidation.AndroidState.ClientMetadata getMetadata();

    // repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
     *
     * <pre>
     * TICL properties stored for this client.
     * </pre>
     */
    java.util.List<com.google.protos.ipc.invalidation.AndroidState.ClientProperty> 
        getPropertyList();
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
     *
     * <pre>
     * TICL properties stored for this client.
     * </pre>
     */
    com.google.protos.ipc.invalidation.AndroidState.ClientProperty getProperty(int index);
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
     *
     * <pre>
     * TICL properties stored for this client.
     * </pre>
     */
    int getPropertyCount();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.StoredState}
   *
   * <pre>
   * The stored state of the client combining base metadata and internal properties.
   * </pre>
   */
  public static final class StoredState extends
      com.google.protobuf.GeneratedMessageLite
      implements StoredStateOrBuilder {
    // Use StoredState.newBuilder() to construct.
    private StoredState(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private StoredState(boolean noInit) {}

    private static final StoredState defaultInstance;
    public static StoredState getDefaultInstance() {
      return defaultInstance;
    }

    public StoredState getDefaultInstanceForType() {
      return defaultInstance;
    }

    private StoredState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = metadata_.toBuilder();
              }
              metadata_ = input.readMessage(com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(metadata_);
                metadata_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                property_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.AndroidState.ClientProperty>();
                mutable_bitField0_ |= 0x00000002;
              }
              property_.add(input.readMessage(com.google.protos.ipc.invalidation.AndroidState.ClientProperty.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          property_ = java.util.Collections.unmodifiableList(property_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<StoredState> PARSER =
        new com.google.protobuf.AbstractParser<StoredState>() {
      public StoredState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StoredState(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StoredState> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;
    public static final int METADATA_FIELD_NUMBER = 1;
    private com.google.protos.ipc.invalidation.AndroidState.ClientMetadata metadata_;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;</code>
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;</code>
     */
    public com.google.protos.ipc.invalidation.AndroidState.ClientMetadata getMetadata() {
      return metadata_;
    }

    // repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;
    public static final int PROPERTY_FIELD_NUMBER = 9;
    private java.util.List<com.google.protos.ipc.invalidation.AndroidState.ClientProperty> property_;
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
     *
     * <pre>
     * TICL properties stored for this client.
     * </pre>
     */
    public java.util.List<com.google.protos.ipc.invalidation.AndroidState.ClientProperty> getPropertyList() {
      return property_;
    }
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
     *
     * <pre>
     * TICL properties stored for this client.
     * </pre>
     */
    public java.util.List<? extends com.google.protos.ipc.invalidation.AndroidState.ClientPropertyOrBuilder> 
        getPropertyOrBuilderList() {
      return property_;
    }
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
     *
     * <pre>
     * TICL properties stored for this client.
     * </pre>
     */
    public int getPropertyCount() {
      return property_.size();
    }
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
     *
     * <pre>
     * TICL properties stored for this client.
     * </pre>
     */
    public com.google.protos.ipc.invalidation.AndroidState.ClientProperty getProperty(int index) {
      return property_.get(index);
    }
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
     *
     * <pre>
     * TICL properties stored for this client.
     * </pre>
     */
    public com.google.protos.ipc.invalidation.AndroidState.ClientPropertyOrBuilder getPropertyOrBuilder(
        int index) {
      return property_.get(index);
    }

    private void initFields() {
      metadata_ = com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.getDefaultInstance();
      property_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, metadata_);
      }
      for (int i = 0; i < property_.size(); i++) {
        output.writeMessage(9, property_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, metadata_);
      }
      for (int i = 0; i < property_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, property_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.AndroidState.StoredState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.StoredState}
     *
     * <pre>
     * The stored state of the client combining base metadata and internal properties.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.AndroidState.StoredState, Builder>
        implements com.google.protos.ipc.invalidation.AndroidState.StoredStateOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.AndroidState.StoredState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        metadata_ = com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        property_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.AndroidState.StoredState getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.AndroidState.StoredState.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.AndroidState.StoredState build() {
        com.google.protos.ipc.invalidation.AndroidState.StoredState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.AndroidState.StoredState buildPartial() {
        com.google.protos.ipc.invalidation.AndroidState.StoredState result = new com.google.protos.ipc.invalidation.AndroidState.StoredState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.metadata_ = metadata_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          property_ = java.util.Collections.unmodifiableList(property_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.property_ = property_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.AndroidState.StoredState other) {
        if (other == com.google.protos.ipc.invalidation.AndroidState.StoredState.getDefaultInstance()) return this;
        if (other.hasMetadata()) {
          mergeMetadata(other.getMetadata());
        }
        if (!other.property_.isEmpty()) {
          if (property_.isEmpty()) {
            property_ = other.property_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePropertyIsMutable();
            property_.addAll(other.property_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.AndroidState.StoredState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.AndroidState.StoredState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;
      private com.google.protos.ipc.invalidation.AndroidState.ClientMetadata metadata_ = com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.getDefaultInstance();
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;</code>
       */
      public boolean hasMetadata() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;</code>
       */
      public com.google.protos.ipc.invalidation.AndroidState.ClientMetadata getMetadata() {
        return metadata_;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;</code>
       */
      public Builder setMetadata(com.google.protos.ipc.invalidation.AndroidState.ClientMetadata value) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;</code>
       */
      public Builder setMetadata(
          com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.Builder builderForValue) {
        metadata_ = builderForValue.build();

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;</code>
       */
      public Builder mergeMetadata(com.google.protos.ipc.invalidation.AndroidState.ClientMetadata value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            metadata_ != com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.getDefaultInstance()) {
          metadata_ =
            com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.newBuilder(metadata_).mergeFrom(value).buildPartial();
        } else {
          metadata_ = value;
        }

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;</code>
       */
      public Builder clearMetadata() {
        metadata_ = com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      // repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;
      private java.util.List<com.google.protos.ipc.invalidation.AndroidState.ClientProperty> property_ =
        java.util.Collections.emptyList();
      private void ensurePropertyIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          property_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.AndroidState.ClientProperty>(property_);
          bitField0_ |= 0x00000002;
         }
      }

      /**
       * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
       *
       * <pre>
       * TICL properties stored for this client.
       * </pre>
       */
      public java.util.List<com.google.protos.ipc.invalidation.AndroidState.ClientProperty> getPropertyList() {
        return java.util.Collections.unmodifiableList(property_);
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
       *
       * <pre>
       * TICL properties stored for this client.
       * </pre>
       */
      public int getPropertyCount() {
        return property_.size();
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
       *
       * <pre>
       * TICL properties stored for this client.
       * </pre>
       */
      public com.google.protos.ipc.invalidation.AndroidState.ClientProperty getProperty(int index) {
        return property_.get(index);
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
       *
       * <pre>
       * TICL properties stored for this client.
       * </pre>
       */
      public Builder setProperty(
          int index, com.google.protos.ipc.invalidation.AndroidState.ClientProperty value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropertyIsMutable();
        property_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
       *
       * <pre>
       * TICL properties stored for this client.
       * </pre>
       */
      public Builder setProperty(
          int index, com.google.protos.ipc.invalidation.AndroidState.ClientProperty.Builder builderForValue) {
        ensurePropertyIsMutable();
        property_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
       *
       * <pre>
       * TICL properties stored for this client.
       * </pre>
       */
      public Builder addProperty(com.google.protos.ipc.invalidation.AndroidState.ClientProperty value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropertyIsMutable();
        property_.add(value);

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
       *
       * <pre>
       * TICL properties stored for this client.
       * </pre>
       */
      public Builder addProperty(
          int index, com.google.protos.ipc.invalidation.AndroidState.ClientProperty value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropertyIsMutable();
        property_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
       *
       * <pre>
       * TICL properties stored for this client.
       * </pre>
       */
      public Builder addProperty(
          com.google.protos.ipc.invalidation.AndroidState.ClientProperty.Builder builderForValue) {
        ensurePropertyIsMutable();
        property_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
       *
       * <pre>
       * TICL properties stored for this client.
       * </pre>
       */
      public Builder addProperty(
          int index, com.google.protos.ipc.invalidation.AndroidState.ClientProperty.Builder builderForValue) {
        ensurePropertyIsMutable();
        property_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
       *
       * <pre>
       * TICL properties stored for this client.
       * </pre>
       */
      public Builder addAllProperty(
          java.lang.Iterable<? extends com.google.protos.ipc.invalidation.AndroidState.ClientProperty> values) {
        ensurePropertyIsMutable();
        super.addAll(values, property_);

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
       *
       * <pre>
       * TICL properties stored for this client.
       * </pre>
       */
      public Builder clearProperty() {
        property_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;</code>
       *
       * <pre>
       * TICL properties stored for this client.
       * </pre>
       */
      public Builder removeProperty(int index) {
        ensurePropertyIsMutable();
        property_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.StoredState)
    }

    static {
      defaultInstance = new StoredState(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.StoredState)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
