// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: android_channel.proto

package com.google.protos.ipc.invalidation;

public final class AndroidChannel {
  private AndroidChannel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code com.google.protos.ipc.invalidation.MajorVersion}
   *
   * <pre>
   * Defines the valid major versions of the android channel protocol.  The
   * channel version controls the expected envelope syntax and semantics of
   * http and c2dm messages sent between the client and server.
   * </pre>
   */
  public enum MajorVersion
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>INITIAL = 0;</code>
     *
     * <pre>
     * The initial version of the android channel protocol.  Inbound and
     * outbound channel packets contained a single binary protocol message only.
     * </pre>
     */
    INITIAL(0, 0),
    /**
     * <code>BATCH = 1;</code>
     *
     * <pre>
     * Adds batching (multiple protocol messages in a single channel message)
     * </pre>
     */
    BATCH(1, 1),
    ;

    /**
     * <code>DEFAULT = 0;</code>
     *
     * <pre>
     * The default channel version used by Android clients.   Lower major numbers
     * will represent earlier versions and higher numbers will represent
     * experimental versions that are not yet released.
     * </pre>
     */
    public static final MajorVersion DEFAULT = INITIAL;
    /**
     * <code>MIN_SUPPORTED = 0;</code>
     *
     * <pre>
     * The minimum and maximum supported channel major versions.  Used to validate
     * incoming requests, so update as new versions are added or old versions are
     * no longer supported.
     * </pre>
     */
    public static final MajorVersion MIN_SUPPORTED = INITIAL;
    /**
     * <code>MAX_SUPPORTED = 1;</code>
     */
    public static final MajorVersion MAX_SUPPORTED = BATCH;
    /**
     * <code>INITIAL = 0;</code>
     *
     * <pre>
     * The initial version of the android channel protocol.  Inbound and
     * outbound channel packets contained a single binary protocol message only.
     * </pre>
     */
    public static final int INITIAL_VALUE = 0;
    /**
     * <code>BATCH = 1;</code>
     *
     * <pre>
     * Adds batching (multiple protocol messages in a single channel message)
     * </pre>
     */
    public static final int BATCH_VALUE = 1;
    /**
     * <code>DEFAULT = 0;</code>
     *
     * <pre>
     * The default channel version used by Android clients.   Lower major numbers
     * will represent earlier versions and higher numbers will represent
     * experimental versions that are not yet released.
     * </pre>
     */
    public static final int DEFAULT_VALUE = 0;
    /**
     * <code>MIN_SUPPORTED = 0;</code>
     *
     * <pre>
     * The minimum and maximum supported channel major versions.  Used to validate
     * incoming requests, so update as new versions are added or old versions are
     * no longer supported.
     * </pre>
     */
    public static final int MIN_SUPPORTED_VALUE = 0;
    /**
     * <code>MAX_SUPPORTED = 1;</code>
     */
    public static final int MAX_SUPPORTED_VALUE = 1;


    public final int getNumber() { return value; }

    public static MajorVersion valueOf(int value) {
      switch (value) {
        case 0: return INITIAL;
        case 1: return BATCH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MajorVersion>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MajorVersion>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MajorVersion>() {
            public MajorVersion findValueByNumber(int number) {
              return MajorVersion.valueOf(number);
            }
          };

    private final int value;

    private MajorVersion(int index, int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.MajorVersion)
  }

  public interface EndpointIdOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional string c2dm_registration_id = 2;
    /**
     * <code>optional string c2dm_registration_id = 2;</code>
     *
     * <pre>
     * The "registration_id" returned when the client registers with c2dm.  This
     * id is required by c2dm in order to send a message to the device.
     * </pre>
     */
    boolean hasC2DmRegistrationId();
    /**
     * <code>optional string c2dm_registration_id = 2;</code>
     *
     * <pre>
     * The "registration_id" returned when the client registers with c2dm.  This
     * id is required by c2dm in order to send a message to the device.
     * </pre>
     */
    java.lang.String getC2DmRegistrationId();
    /**
     * <code>optional string c2dm_registration_id = 2;</code>
     *
     * <pre>
     * The "registration_id" returned when the client registers with c2dm.  This
     * id is required by c2dm in order to send a message to the device.
     * </pre>
     */
    com.google.protobuf.ByteString
        getC2DmRegistrationIdBytes();

    // optional string client_key = 3;
    /**
     * <code>optional string client_key = 3;</code>
     *
     * <pre>
     * A key identifying a specific client on a device.
     * </pre>
     */
    boolean hasClientKey();
    /**
     * <code>optional string client_key = 3;</code>
     *
     * <pre>
     * A key identifying a specific client on a device.
     * </pre>
     */
    java.lang.String getClientKey();
    /**
     * <code>optional string client_key = 3;</code>
     *
     * <pre>
     * A key identifying a specific client on a device.
     * </pre>
     */
    com.google.protobuf.ByteString
        getClientKeyBytes();

    // optional string sender_id = 4 [deprecated = true];
    /**
     * <code>optional string sender_id = 4 [deprecated = true];</code>
     *
     * <pre>
     * The C2DM sender ID to use to deliver messages to the endpoint.
     * </pre>
     */
    @java.lang.Deprecated boolean hasSenderId();
    /**
     * <code>optional string sender_id = 4 [deprecated = true];</code>
     *
     * <pre>
     * The C2DM sender ID to use to deliver messages to the endpoint.
     * </pre>
     */
    @java.lang.Deprecated java.lang.String getSenderId();
    /**
     * <code>optional string sender_id = 4 [deprecated = true];</code>
     *
     * <pre>
     * The C2DM sender ID to use to deliver messages to the endpoint.
     * </pre>
     */
    @java.lang.Deprecated com.google.protobuf.ByteString
        getSenderIdBytes();

    // optional .com.google.protos.ipc.invalidation.Version channel_version = 5;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.Version channel_version = 5;</code>
     *
     * <pre>
     * Defines the expected channel version generated by the network endpoint or
     * expected in messages sent from the server.
     * </pre>
     */
    boolean hasChannelVersion();
    /**
     * <code>optional .com.google.protos.ipc.invalidation.Version channel_version = 5;</code>
     *
     * <pre>
     * Defines the expected channel version generated by the network endpoint or
     * expected in messages sent from the server.
     * </pre>
     */
    com.google.protos.ipc.invalidation.ClientProtocol.Version getChannelVersion();

    // optional string package_name = 6;
    /**
     * <code>optional string package_name = 6;</code>
     *
     * <pre>
     * The package name of the Android application that will receive the messages.
     * Replaces sender_id. Must be set (unless sender_id is set; in which case it
     * must not be set).
     * </pre>
     */
    boolean hasPackageName();
    /**
     * <code>optional string package_name = 6;</code>
     *
     * <pre>
     * The package name of the Android application that will receive the messages.
     * Replaces sender_id. Must be set (unless sender_id is set; in which case it
     * must not be set).
     * </pre>
     */
    java.lang.String getPackageName();
    /**
     * <code>optional string package_name = 6;</code>
     *
     * <pre>
     * The package name of the Android application that will receive the messages.
     * Replaces sender_id. Must be set (unless sender_id is set; in which case it
     * must not be set).
     * </pre>
     */
    com.google.protobuf.ByteString
        getPackageNameBytes();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.EndpointId}
   *
   * <pre>
   * An id that specifies how to route a message to a Ticl on an Android device
   * via C2DM.
   * </pre>
   */
  public static final class EndpointId extends
      com.google.protobuf.GeneratedMessageLite
      implements EndpointIdOrBuilder {
    // Use EndpointId.newBuilder() to construct.
    private EndpointId(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private EndpointId(boolean noInit) {}

    private static final EndpointId defaultInstance;
    public static EndpointId getDefaultInstance() {
      return defaultInstance;
    }

    public EndpointId getDefaultInstanceForType() {
      return defaultInstance;
    }

    private EndpointId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              c2DmRegistrationId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              clientKey_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              senderId_ = input.readBytes();
              break;
            }
            case 42: {
              com.google.protos.ipc.invalidation.ClientProtocol.Version.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = channelVersion_.toBuilder();
              }
              channelVersion_ = input.readMessage(com.google.protos.ipc.invalidation.ClientProtocol.Version.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(channelVersion_);
                channelVersion_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              packageName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<EndpointId> PARSER =
        new com.google.protobuf.AbstractParser<EndpointId>() {
      public EndpointId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EndpointId(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EndpointId> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string c2dm_registration_id = 2;
    public static final int C2DM_REGISTRATION_ID_FIELD_NUMBER = 2;
    private java.lang.Object c2DmRegistrationId_;
    /**
     * <code>optional string c2dm_registration_id = 2;</code>
     *
     * <pre>
     * The "registration_id" returned when the client registers with c2dm.  This
     * id is required by c2dm in order to send a message to the device.
     * </pre>
     */
    public boolean hasC2DmRegistrationId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string c2dm_registration_id = 2;</code>
     *
     * <pre>
     * The "registration_id" returned when the client registers with c2dm.  This
     * id is required by c2dm in order to send a message to the device.
     * </pre>
     */
    public java.lang.String getC2DmRegistrationId() {
      java.lang.Object ref = c2DmRegistrationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c2DmRegistrationId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c2dm_registration_id = 2;</code>
     *
     * <pre>
     * The "registration_id" returned when the client registers with c2dm.  This
     * id is required by c2dm in order to send a message to the device.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getC2DmRegistrationIdBytes() {
      java.lang.Object ref = c2DmRegistrationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c2DmRegistrationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string client_key = 3;
    public static final int CLIENT_KEY_FIELD_NUMBER = 3;
    private java.lang.Object clientKey_;
    /**
     * <code>optional string client_key = 3;</code>
     *
     * <pre>
     * A key identifying a specific client on a device.
     * </pre>
     */
    public boolean hasClientKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string client_key = 3;</code>
     *
     * <pre>
     * A key identifying a specific client on a device.
     * </pre>
     */
    public java.lang.String getClientKey() {
      java.lang.Object ref = clientKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string client_key = 3;</code>
     *
     * <pre>
     * A key identifying a specific client on a device.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClientKeyBytes() {
      java.lang.Object ref = clientKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string sender_id = 4 [deprecated = true];
    public static final int SENDER_ID_FIELD_NUMBER = 4;
    private java.lang.Object senderId_;
    /**
     * <code>optional string sender_id = 4 [deprecated = true];</code>
     *
     * <pre>
     * The C2DM sender ID to use to deliver messages to the endpoint.
     * </pre>
     */
    @java.lang.Deprecated public boolean hasSenderId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string sender_id = 4 [deprecated = true];</code>
     *
     * <pre>
     * The C2DM sender ID to use to deliver messages to the endpoint.
     * </pre>
     */
    @java.lang.Deprecated public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sender_id = 4 [deprecated = true];</code>
     *
     * <pre>
     * The C2DM sender ID to use to deliver messages to the endpoint.
     * </pre>
     */
    @java.lang.Deprecated public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .com.google.protos.ipc.invalidation.Version channel_version = 5;
    public static final int CHANNEL_VERSION_FIELD_NUMBER = 5;
    private com.google.protos.ipc.invalidation.ClientProtocol.Version channelVersion_;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.Version channel_version = 5;</code>
     *
     * <pre>
     * Defines the expected channel version generated by the network endpoint or
     * expected in messages sent from the server.
     * </pre>
     */
    public boolean hasChannelVersion() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.google.protos.ipc.invalidation.Version channel_version = 5;</code>
     *
     * <pre>
     * Defines the expected channel version generated by the network endpoint or
     * expected in messages sent from the server.
     * </pre>
     */
    public com.google.protos.ipc.invalidation.ClientProtocol.Version getChannelVersion() {
      return channelVersion_;
    }

    // optional string package_name = 6;
    public static final int PACKAGE_NAME_FIELD_NUMBER = 6;
    private java.lang.Object packageName_;
    /**
     * <code>optional string package_name = 6;</code>
     *
     * <pre>
     * The package name of the Android application that will receive the messages.
     * Replaces sender_id. Must be set (unless sender_id is set; in which case it
     * must not be set).
     * </pre>
     */
    public boolean hasPackageName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string package_name = 6;</code>
     *
     * <pre>
     * The package name of the Android application that will receive the messages.
     * Replaces sender_id. Must be set (unless sender_id is set; in which case it
     * must not be set).
     * </pre>
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packageName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string package_name = 6;</code>
     *
     * <pre>
     * The package name of the Android application that will receive the messages.
     * Replaces sender_id. Must be set (unless sender_id is set; in which case it
     * must not be set).
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      c2DmRegistrationId_ = "";
      clientKey_ = "";
      senderId_ = "";
      channelVersion_ = com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance();
      packageName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getC2DmRegistrationIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getClientKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getSenderIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(5, channelVersion_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getPackageNameBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getC2DmRegistrationIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getClientKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSenderIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, channelVersion_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPackageNameBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.AndroidChannel.EndpointId prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.EndpointId}
     *
     * <pre>
     * An id that specifies how to route a message to a Ticl on an Android device
     * via C2DM.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.AndroidChannel.EndpointId, Builder>
        implements com.google.protos.ipc.invalidation.AndroidChannel.EndpointIdOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.AndroidChannel.EndpointId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        c2DmRegistrationId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        clientKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        senderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        channelVersion_ = com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000008);
        packageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.AndroidChannel.EndpointId getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.AndroidChannel.EndpointId.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.AndroidChannel.EndpointId build() {
        com.google.protos.ipc.invalidation.AndroidChannel.EndpointId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.AndroidChannel.EndpointId buildPartial() {
        com.google.protos.ipc.invalidation.AndroidChannel.EndpointId result = new com.google.protos.ipc.invalidation.AndroidChannel.EndpointId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.c2DmRegistrationId_ = c2DmRegistrationId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientKey_ = clientKey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.senderId_ = senderId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.channelVersion_ = channelVersion_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.packageName_ = packageName_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.AndroidChannel.EndpointId other) {
        if (other == com.google.protos.ipc.invalidation.AndroidChannel.EndpointId.getDefaultInstance()) return this;
        if (other.hasC2DmRegistrationId()) {
          bitField0_ |= 0x00000001;
          c2DmRegistrationId_ = other.c2DmRegistrationId_;
          
        }
        if (other.hasClientKey()) {
          bitField0_ |= 0x00000002;
          clientKey_ = other.clientKey_;
          
        }
        if (other.hasSenderId()) {
          bitField0_ |= 0x00000004;
          senderId_ = other.senderId_;
          
        }
        if (other.hasChannelVersion()) {
          mergeChannelVersion(other.getChannelVersion());
        }
        if (other.hasPackageName()) {
          bitField0_ |= 0x00000010;
          packageName_ = other.packageName_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.AndroidChannel.EndpointId) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string c2dm_registration_id = 2;
      private java.lang.Object c2DmRegistrationId_ = "";
      /**
       * <code>optional string c2dm_registration_id = 2;</code>
       *
       * <pre>
       * The "registration_id" returned when the client registers with c2dm.  This
       * id is required by c2dm in order to send a message to the device.
       * </pre>
       */
      public boolean hasC2DmRegistrationId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string c2dm_registration_id = 2;</code>
       *
       * <pre>
       * The "registration_id" returned when the client registers with c2dm.  This
       * id is required by c2dm in order to send a message to the device.
       * </pre>
       */
      public java.lang.String getC2DmRegistrationId() {
        java.lang.Object ref = c2DmRegistrationId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c2DmRegistrationId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c2dm_registration_id = 2;</code>
       *
       * <pre>
       * The "registration_id" returned when the client registers with c2dm.  This
       * id is required by c2dm in order to send a message to the device.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getC2DmRegistrationIdBytes() {
        java.lang.Object ref = c2DmRegistrationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c2DmRegistrationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c2dm_registration_id = 2;</code>
       *
       * <pre>
       * The "registration_id" returned when the client registers with c2dm.  This
       * id is required by c2dm in order to send a message to the device.
       * </pre>
       */
      public Builder setC2DmRegistrationId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        c2DmRegistrationId_ = value;
        
        return this;
      }
      /**
       * <code>optional string c2dm_registration_id = 2;</code>
       *
       * <pre>
       * The "registration_id" returned when the client registers with c2dm.  This
       * id is required by c2dm in order to send a message to the device.
       * </pre>
       */
      public Builder clearC2DmRegistrationId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        c2DmRegistrationId_ = getDefaultInstance().getC2DmRegistrationId();
        
        return this;
      }
      /**
       * <code>optional string c2dm_registration_id = 2;</code>
       *
       * <pre>
       * The "registration_id" returned when the client registers with c2dm.  This
       * id is required by c2dm in order to send a message to the device.
       * </pre>
       */
      public Builder setC2DmRegistrationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        c2DmRegistrationId_ = value;
        
        return this;
      }

      // optional string client_key = 3;
      private java.lang.Object clientKey_ = "";
      /**
       * <code>optional string client_key = 3;</code>
       *
       * <pre>
       * A key identifying a specific client on a device.
       * </pre>
       */
      public boolean hasClientKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string client_key = 3;</code>
       *
       * <pre>
       * A key identifying a specific client on a device.
       * </pre>
       */
      public java.lang.String getClientKey() {
        java.lang.Object ref = clientKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clientKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string client_key = 3;</code>
       *
       * <pre>
       * A key identifying a specific client on a device.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClientKeyBytes() {
        java.lang.Object ref = clientKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string client_key = 3;</code>
       *
       * <pre>
       * A key identifying a specific client on a device.
       * </pre>
       */
      public Builder setClientKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientKey_ = value;
        
        return this;
      }
      /**
       * <code>optional string client_key = 3;</code>
       *
       * <pre>
       * A key identifying a specific client on a device.
       * </pre>
       */
      public Builder clearClientKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientKey_ = getDefaultInstance().getClientKey();
        
        return this;
      }
      /**
       * <code>optional string client_key = 3;</code>
       *
       * <pre>
       * A key identifying a specific client on a device.
       * </pre>
       */
      public Builder setClientKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientKey_ = value;
        
        return this;
      }

      // optional string sender_id = 4 [deprecated = true];
      private java.lang.Object senderId_ = "";
      /**
       * <code>optional string sender_id = 4 [deprecated = true];</code>
       *
       * <pre>
       * The C2DM sender ID to use to deliver messages to the endpoint.
       * </pre>
       */
      @java.lang.Deprecated public boolean hasSenderId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string sender_id = 4 [deprecated = true];</code>
       *
       * <pre>
       * The C2DM sender ID to use to deliver messages to the endpoint.
       * </pre>
       */
      @java.lang.Deprecated public java.lang.String getSenderId() {
        java.lang.Object ref = senderId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          senderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sender_id = 4 [deprecated = true];</code>
       *
       * <pre>
       * The C2DM sender ID to use to deliver messages to the endpoint.
       * </pre>
       */
      @java.lang.Deprecated public com.google.protobuf.ByteString
          getSenderIdBytes() {
        java.lang.Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sender_id = 4 [deprecated = true];</code>
       *
       * <pre>
       * The C2DM sender ID to use to deliver messages to the endpoint.
       * </pre>
       */
      @java.lang.Deprecated public Builder setSenderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        senderId_ = value;
        
        return this;
      }
      /**
       * <code>optional string sender_id = 4 [deprecated = true];</code>
       *
       * <pre>
       * The C2DM sender ID to use to deliver messages to the endpoint.
       * </pre>
       */
      @java.lang.Deprecated public Builder clearSenderId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        senderId_ = getDefaultInstance().getSenderId();
        
        return this;
      }
      /**
       * <code>optional string sender_id = 4 [deprecated = true];</code>
       *
       * <pre>
       * The C2DM sender ID to use to deliver messages to the endpoint.
       * </pre>
       */
      @java.lang.Deprecated public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        senderId_ = value;
        
        return this;
      }

      // optional .com.google.protos.ipc.invalidation.Version channel_version = 5;
      private com.google.protos.ipc.invalidation.ClientProtocol.Version channelVersion_ = com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance();
      /**
       * <code>optional .com.google.protos.ipc.invalidation.Version channel_version = 5;</code>
       *
       * <pre>
       * Defines the expected channel version generated by the network endpoint or
       * expected in messages sent from the server.
       * </pre>
       */
      public boolean hasChannelVersion() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.Version channel_version = 5;</code>
       *
       * <pre>
       * Defines the expected channel version generated by the network endpoint or
       * expected in messages sent from the server.
       * </pre>
       */
      public com.google.protos.ipc.invalidation.ClientProtocol.Version getChannelVersion() {
        return channelVersion_;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.Version channel_version = 5;</code>
       *
       * <pre>
       * Defines the expected channel version generated by the network endpoint or
       * expected in messages sent from the server.
       * </pre>
       */
      public Builder setChannelVersion(com.google.protos.ipc.invalidation.ClientProtocol.Version value) {
        if (value == null) {
          throw new NullPointerException();
        }
        channelVersion_ = value;

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.Version channel_version = 5;</code>
       *
       * <pre>
       * Defines the expected channel version generated by the network endpoint or
       * expected in messages sent from the server.
       * </pre>
       */
      public Builder setChannelVersion(
          com.google.protos.ipc.invalidation.ClientProtocol.Version.Builder builderForValue) {
        channelVersion_ = builderForValue.build();

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.Version channel_version = 5;</code>
       *
       * <pre>
       * Defines the expected channel version generated by the network endpoint or
       * expected in messages sent from the server.
       * </pre>
       */
      public Builder mergeChannelVersion(com.google.protos.ipc.invalidation.ClientProtocol.Version value) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            channelVersion_ != com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance()) {
          channelVersion_ =
            com.google.protos.ipc.invalidation.ClientProtocol.Version.newBuilder(channelVersion_).mergeFrom(value).buildPartial();
        } else {
          channelVersion_ = value;
        }

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.Version channel_version = 5;</code>
       *
       * <pre>
       * Defines the expected channel version generated by the network endpoint or
       * expected in messages sent from the server.
       * </pre>
       */
      public Builder clearChannelVersion() {
        channelVersion_ = com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      // optional string package_name = 6;
      private java.lang.Object packageName_ = "";
      /**
       * <code>optional string package_name = 6;</code>
       *
       * <pre>
       * The package name of the Android application that will receive the messages.
       * Replaces sender_id. Must be set (unless sender_id is set; in which case it
       * must not be set).
       * </pre>
       */
      public boolean hasPackageName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string package_name = 6;</code>
       *
       * <pre>
       * The package name of the Android application that will receive the messages.
       * Replaces sender_id. Must be set (unless sender_id is set; in which case it
       * must not be set).
       * </pre>
       */
      public java.lang.String getPackageName() {
        java.lang.Object ref = packageName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          packageName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string package_name = 6;</code>
       *
       * <pre>
       * The package name of the Android application that will receive the messages.
       * Replaces sender_id. Must be set (unless sender_id is set; in which case it
       * must not be set).
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPackageNameBytes() {
        java.lang.Object ref = packageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string package_name = 6;</code>
       *
       * <pre>
       * The package name of the Android application that will receive the messages.
       * Replaces sender_id. Must be set (unless sender_id is set; in which case it
       * must not be set).
       * </pre>
       */
      public Builder setPackageName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        packageName_ = value;
        
        return this;
      }
      /**
       * <code>optional string package_name = 6;</code>
       *
       * <pre>
       * The package name of the Android application that will receive the messages.
       * Replaces sender_id. Must be set (unless sender_id is set; in which case it
       * must not be set).
       * </pre>
       */
      public Builder clearPackageName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        packageName_ = getDefaultInstance().getPackageName();
        
        return this;
      }
      /**
       * <code>optional string package_name = 6;</code>
       *
       * <pre>
       * The package name of the Android application that will receive the messages.
       * Replaces sender_id. Must be set (unless sender_id is set; in which case it
       * must not be set).
       * </pre>
       */
      public Builder setPackageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        packageName_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.EndpointId)
    }

    static {
      defaultInstance = new EndpointId(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.EndpointId)
  }

  public interface AddressedAndroidMessageOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional string client_key = 1;
    /**
     * <code>optional string client_key = 1;</code>
     *
     * <pre>
     * Client on the device to which the message is destined.
     * </pre>
     */
    boolean hasClientKey();
    /**
     * <code>optional string client_key = 1;</code>
     *
     * <pre>
     * Client on the device to which the message is destined.
     * </pre>
     */
    java.lang.String getClientKey();
    /**
     * <code>optional string client_key = 1;</code>
     *
     * <pre>
     * Client on the device to which the message is destined.
     * </pre>
     */
    com.google.protobuf.ByteString
        getClientKeyBytes();

    // optional bytes message = 2;
    /**
     * <code>optional bytes message = 2;</code>
     *
     * <pre>
     * Message contents (serialized ServerToClientMessage).
     * </pre>
     */
    boolean hasMessage();
    /**
     * <code>optional bytes message = 2;</code>
     *
     * <pre>
     * Message contents (serialized ServerToClientMessage).
     * </pre>
     */
    com.google.protobuf.ByteString getMessage();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.AddressedAndroidMessage}
   *
   * <pre>
   * A message addressed to a particular Ticl on an Android device.
   * </pre>
   */
  public static final class AddressedAndroidMessage extends
      com.google.protobuf.GeneratedMessageLite
      implements AddressedAndroidMessageOrBuilder {
    // Use AddressedAndroidMessage.newBuilder() to construct.
    private AddressedAndroidMessage(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private AddressedAndroidMessage(boolean noInit) {}

    private static final AddressedAndroidMessage defaultInstance;
    public static AddressedAndroidMessage getDefaultInstance() {
      return defaultInstance;
    }

    public AddressedAndroidMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private AddressedAndroidMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              clientKey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<AddressedAndroidMessage> PARSER =
        new com.google.protobuf.AbstractParser<AddressedAndroidMessage>() {
      public AddressedAndroidMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressedAndroidMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddressedAndroidMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string client_key = 1;
    public static final int CLIENT_KEY_FIELD_NUMBER = 1;
    private java.lang.Object clientKey_;
    /**
     * <code>optional string client_key = 1;</code>
     *
     * <pre>
     * Client on the device to which the message is destined.
     * </pre>
     */
    public boolean hasClientKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string client_key = 1;</code>
     *
     * <pre>
     * Client on the device to which the message is destined.
     * </pre>
     */
    public java.lang.String getClientKey() {
      java.lang.Object ref = clientKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string client_key = 1;</code>
     *
     * <pre>
     * Client on the device to which the message is destined.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClientKeyBytes() {
      java.lang.Object ref = clientKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>optional bytes message = 2;</code>
     *
     * <pre>
     * Message contents (serialized ServerToClientMessage).
     * </pre>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes message = 2;</code>
     *
     * <pre>
     * Message contents (serialized ServerToClientMessage).
     * </pre>
     */
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    private void initFields() {
      clientKey_ = "";
      message_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getClientKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, message_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClientKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, message_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.AddressedAndroidMessage}
     *
     * <pre>
     * A message addressed to a particular Ticl on an Android device.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage, Builder>
        implements com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clientKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage build() {
        com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage buildPartial() {
        com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage result = new com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientKey_ = clientKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage other) {
        if (other == com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.getDefaultInstance()) return this;
        if (other.hasClientKey()) {
          bitField0_ |= 0x00000001;
          clientKey_ = other.clientKey_;
          
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string client_key = 1;
      private java.lang.Object clientKey_ = "";
      /**
       * <code>optional string client_key = 1;</code>
       *
       * <pre>
       * Client on the device to which the message is destined.
       * </pre>
       */
      public boolean hasClientKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string client_key = 1;</code>
       *
       * <pre>
       * Client on the device to which the message is destined.
       * </pre>
       */
      public java.lang.String getClientKey() {
        java.lang.Object ref = clientKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clientKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string client_key = 1;</code>
       *
       * <pre>
       * Client on the device to which the message is destined.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClientKeyBytes() {
        java.lang.Object ref = clientKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string client_key = 1;</code>
       *
       * <pre>
       * Client on the device to which the message is destined.
       * </pre>
       */
      public Builder setClientKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientKey_ = value;
        
        return this;
      }
      /**
       * <code>optional string client_key = 1;</code>
       *
       * <pre>
       * Client on the device to which the message is destined.
       * </pre>
       */
      public Builder clearClientKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientKey_ = getDefaultInstance().getClientKey();
        
        return this;
      }
      /**
       * <code>optional string client_key = 1;</code>
       *
       * <pre>
       * Client on the device to which the message is destined.
       * </pre>
       */
      public Builder setClientKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientKey_ = value;
        
        return this;
      }

      // optional bytes message = 2;
      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes message = 2;</code>
       *
       * <pre>
       * Message contents (serialized ServerToClientMessage).
       * </pre>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes message = 2;</code>
       *
       * <pre>
       * Message contents (serialized ServerToClientMessage).
       * </pre>
       */
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <code>optional bytes message = 2;</code>
       *
       * <pre>
       * Message contents (serialized ServerToClientMessage).
       * </pre>
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes message = 2;</code>
       *
       * <pre>
       * Message contents (serialized ServerToClientMessage).
       * </pre>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.AddressedAndroidMessage)
    }

    static {
      defaultInstance = new AddressedAndroidMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.AddressedAndroidMessage)
  }

  public interface AddressedAndroidMessageBatchOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
     */
    java.util.List<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage> 
        getAddressedMessageList();
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
     */
    com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage getAddressedMessage(int index);
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
     */
    int getAddressedMessageCount();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.AddressedAndroidMessageBatch}
   *
   * <pre>
   * A batch of messages addressed to potentially-different Ticls on the same
   * Android device.
   * </pre>
   */
  public static final class AddressedAndroidMessageBatch extends
      com.google.protobuf.GeneratedMessageLite
      implements AddressedAndroidMessageBatchOrBuilder {
    // Use AddressedAndroidMessageBatch.newBuilder() to construct.
    private AddressedAndroidMessageBatch(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private AddressedAndroidMessageBatch(boolean noInit) {}

    private static final AddressedAndroidMessageBatch defaultInstance;
    public static AddressedAndroidMessageBatch getDefaultInstance() {
      return defaultInstance;
    }

    public AddressedAndroidMessageBatch getDefaultInstanceForType() {
      return defaultInstance;
    }

    private AddressedAndroidMessageBatch(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                addressedMessage_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              addressedMessage_.add(input.readMessage(com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          addressedMessage_ = java.util.Collections.unmodifiableList(addressedMessage_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<AddressedAndroidMessageBatch> PARSER =
        new com.google.protobuf.AbstractParser<AddressedAndroidMessageBatch>() {
      public AddressedAndroidMessageBatch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressedAndroidMessageBatch(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddressedAndroidMessageBatch> getParserForType() {
      return PARSER;
    }

    // repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;
    public static final int ADDRESSED_MESSAGE_FIELD_NUMBER = 1;
    private java.util.List<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage> addressedMessage_;
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
     */
    public java.util.List<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage> getAddressedMessageList() {
      return addressedMessage_;
    }
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
     */
    public java.util.List<? extends com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageOrBuilder> 
        getAddressedMessageOrBuilderList() {
      return addressedMessage_;
    }
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
     */
    public int getAddressedMessageCount() {
      return addressedMessage_.size();
    }
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
     */
    public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage getAddressedMessage(int index) {
      return addressedMessage_.get(index);
    }
    /**
     * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
     */
    public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageOrBuilder getAddressedMessageOrBuilder(
        int index) {
      return addressedMessage_.get(index);
    }

    private void initFields() {
      addressedMessage_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < addressedMessage_.size(); i++) {
        output.writeMessage(1, addressedMessage_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < addressedMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, addressedMessage_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.AddressedAndroidMessageBatch}
     *
     * <pre>
     * A batch of messages addressed to potentially-different Ticls on the same
     * Android device.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch, Builder>
        implements com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatchOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        addressedMessage_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch build() {
        com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch buildPartial() {
        com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch result = new com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          addressedMessage_ = java.util.Collections.unmodifiableList(addressedMessage_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.addressedMessage_ = addressedMessage_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch other) {
        if (other == com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch.getDefaultInstance()) return this;
        if (!other.addressedMessage_.isEmpty()) {
          if (addressedMessage_.isEmpty()) {
            addressedMessage_ = other.addressedMessage_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAddressedMessageIsMutable();
            addressedMessage_.addAll(other.addressedMessage_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;
      private java.util.List<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage> addressedMessage_ =
        java.util.Collections.emptyList();
      private void ensureAddressedMessageIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          addressedMessage_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage>(addressedMessage_);
          bitField0_ |= 0x00000001;
         }
      }

      /**
       * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
       */
      public java.util.List<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage> getAddressedMessageList() {
        return java.util.Collections.unmodifiableList(addressedMessage_);
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
       */
      public int getAddressedMessageCount() {
        return addressedMessage_.size();
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
       */
      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage getAddressedMessage(int index) {
        return addressedMessage_.get(index);
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
       */
      public Builder setAddressedMessage(
          int index, com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressedMessageIsMutable();
        addressedMessage_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
       */
      public Builder setAddressedMessage(
          int index, com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.Builder builderForValue) {
        ensureAddressedMessageIsMutable();
        addressedMessage_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
       */
      public Builder addAddressedMessage(com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressedMessageIsMutable();
        addressedMessage_.add(value);

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
       */
      public Builder addAddressedMessage(
          int index, com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressedMessageIsMutable();
        addressedMessage_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
       */
      public Builder addAddressedMessage(
          com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.Builder builderForValue) {
        ensureAddressedMessageIsMutable();
        addressedMessage_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
       */
      public Builder addAddressedMessage(
          int index, com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.Builder builderForValue) {
        ensureAddressedMessageIsMutable();
        addressedMessage_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
       */
      public Builder addAllAddressedMessage(
          java.lang.Iterable<? extends com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage> values) {
        ensureAddressedMessageIsMutable();
        super.addAll(values, addressedMessage_);

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
       */
      public Builder clearAddressedMessage() {
        addressedMessage_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);

        return this;
      }
      /**
       * <code>repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;</code>
       */
      public Builder removeAddressedMessage(int index) {
        ensureAddressedMessageIsMutable();
        addressedMessage_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.AddressedAndroidMessageBatch)
    }

    static {
      defaultInstance = new AddressedAndroidMessageBatch(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.AddressedAndroidMessageBatch)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
