// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel.proto

package com.google.protos.ipc.invalidation;

public final class Channel {
  private Channel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NetworkEndpointIdOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;</code>
     */
    boolean hasNetworkAddress();
    /**
     * <code>optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;</code>
     */
    com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress getNetworkAddress();

    // optional bytes client_address = 2;
    /**
     * <code>optional bytes client_address = 2;</code>
     */
    boolean hasClientAddress();
    /**
     * <code>optional bytes client_address = 2;</code>
     */
    com.google.protobuf.ByteString getClientAddress();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.NetworkEndpointId}
   */
  public static final class NetworkEndpointId extends
      com.google.protobuf.GeneratedMessageLite
      implements NetworkEndpointIdOrBuilder {
    // Use NetworkEndpointId.newBuilder() to construct.
    private NetworkEndpointId(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private NetworkEndpointId(boolean noInit) {}

    private static final NetworkEndpointId defaultInstance;
    public static NetworkEndpointId getDefaultInstance() {
      return defaultInstance;
    }

    public NetworkEndpointId getDefaultInstanceForType() {
      return defaultInstance;
    }

    private NetworkEndpointId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress value = com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                networkAddress_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              clientAddress_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<NetworkEndpointId> PARSER =
        new com.google.protobuf.AbstractParser<NetworkEndpointId>() {
      public NetworkEndpointId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetworkEndpointId(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NetworkEndpointId> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress}
     */
    public enum NetworkAddress
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>TEST = 1;</code>
       *
       * <pre>
       * A delivery service for testing
       * </pre>
       */
      TEST(0, 1),
      /**
       * <code>ANDROID = 113;</code>
       *
       * <pre>
       * Low numbers reserved.
       * </pre>
       */
      ANDROID(1, 113),
      /**
       * <code>LCS = 114;</code>
       *
       * <pre>
       * Lightweight connection service (Marmoset) channel.
       * </pre>
       */
      LCS(2, 114),
      ;

      /**
       * <code>TEST = 1;</code>
       *
       * <pre>
       * A delivery service for testing
       * </pre>
       */
      public static final int TEST_VALUE = 1;
      /**
       * <code>ANDROID = 113;</code>
       *
       * <pre>
       * Low numbers reserved.
       * </pre>
       */
      public static final int ANDROID_VALUE = 113;
      /**
       * <code>LCS = 114;</code>
       *
       * <pre>
       * Lightweight connection service (Marmoset) channel.
       * </pre>
       */
      public static final int LCS_VALUE = 114;


      public final int getNumber() { return value; }

      public static NetworkAddress valueOf(int value) {
        switch (value) {
          case 1: return TEST;
          case 113: return ANDROID;
          case 114: return LCS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NetworkAddress>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<NetworkAddress>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NetworkAddress>() {
              public NetworkAddress findValueByNumber(int number) {
                return NetworkAddress.valueOf(number);
              }
            };

      private final int value;

      private NetworkAddress(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress)
    }

    private int bitField0_;
    // optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;
    public static final int NETWORK_ADDRESS_FIELD_NUMBER = 1;
    private com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress networkAddress_;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;</code>
     */
    public boolean hasNetworkAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;</code>
     */
    public com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress getNetworkAddress() {
      return networkAddress_;
    }

    // optional bytes client_address = 2;
    public static final int CLIENT_ADDRESS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString clientAddress_;
    /**
     * <code>optional bytes client_address = 2;</code>
     */
    public boolean hasClientAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes client_address = 2;</code>
     */
    public com.google.protobuf.ByteString getClientAddress() {
      return clientAddress_;
    }

    private void initFields() {
      networkAddress_ = com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress.TEST;
      clientAddress_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, networkAddress_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, clientAddress_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, networkAddress_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, clientAddress_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Channel.NetworkEndpointId prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.NetworkEndpointId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Channel.NetworkEndpointId, Builder>
        implements com.google.protos.ipc.invalidation.Channel.NetworkEndpointIdOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        networkAddress_ = com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress.TEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        clientAddress_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.Channel.NetworkEndpointId getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.Channel.NetworkEndpointId build() {
        com.google.protos.ipc.invalidation.Channel.NetworkEndpointId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.Channel.NetworkEndpointId buildPartial() {
        com.google.protos.ipc.invalidation.Channel.NetworkEndpointId result = new com.google.protos.ipc.invalidation.Channel.NetworkEndpointId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.networkAddress_ = networkAddress_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientAddress_ = clientAddress_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.Channel.NetworkEndpointId other) {
        if (other == com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.getDefaultInstance()) return this;
        if (other.hasNetworkAddress()) {
          setNetworkAddress(other.getNetworkAddress());
        }
        if (other.hasClientAddress()) {
          setClientAddress(other.getClientAddress());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.Channel.NetworkEndpointId) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;
      private com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress networkAddress_ = com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress.TEST;
      /**
       * <code>optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;</code>
       */
      public boolean hasNetworkAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;</code>
       */
      public com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress getNetworkAddress() {
        return networkAddress_;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;</code>
       */
      public Builder setNetworkAddress(com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        networkAddress_ = value;
        
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;</code>
       */
      public Builder clearNetworkAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        networkAddress_ = com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress.TEST;
        
        return this;
      }

      // optional bytes client_address = 2;
      private com.google.protobuf.ByteString clientAddress_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes client_address = 2;</code>
       */
      public boolean hasClientAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes client_address = 2;</code>
       */
      public com.google.protobuf.ByteString getClientAddress() {
        return clientAddress_;
      }
      /**
       * <code>optional bytes client_address = 2;</code>
       */
      public Builder setClientAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientAddress_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes client_address = 2;</code>
       */
      public Builder clearClientAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientAddress_ = getDefaultInstance().getClientAddress();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.NetworkEndpointId)
    }

    static {
      defaultInstance = new NetworkEndpointId(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.NetworkEndpointId)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
