// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel_common.proto

package com.google.protos.ipc.invalidation;

public final class ChannelCommon {
  private ChannelCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ChannelMessageEncodingOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.ChannelMessageEncoding}
   */
  public static final class ChannelMessageEncoding extends
      com.google.protobuf.GeneratedMessageLite
      implements ChannelMessageEncodingOrBuilder {
    // Use ChannelMessageEncoding.newBuilder() to construct.
    private ChannelMessageEncoding(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private ChannelMessageEncoding(boolean noInit) {}

    private static final ChannelMessageEncoding defaultInstance;
    public static ChannelMessageEncoding getDefaultInstance() {
      return defaultInstance;
    }

    public ChannelMessageEncoding getDefaultInstanceForType() {
      return defaultInstance;
    }

    private ChannelMessageEncoding(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<ChannelMessageEncoding> PARSER =
        new com.google.protobuf.AbstractParser<ChannelMessageEncoding>() {
      public ChannelMessageEncoding parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChannelMessageEncoding(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChannelMessageEncoding> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.google.protos.ipc.invalidation.ChannelMessageEncoding.MessageEncoding}
     *
     * <pre>
     * What kind of encoding is used for network_message
     * </pre>
     */
    public enum MessageEncoding
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>PROTOBUF_BINARY_FORMAT = 1;</code>
       *
       * <pre>
       * Raw proto encoding
       * </pre>
       */
      PROTOBUF_BINARY_FORMAT(0, 1),
      ;

      /**
       * <code>PROTOBUF_BINARY_FORMAT = 1;</code>
       *
       * <pre>
       * Raw proto encoding
       * </pre>
       */
      public static final int PROTOBUF_BINARY_FORMAT_VALUE = 1;


      public final int getNumber() { return value; }

      public static MessageEncoding valueOf(int value) {
        switch (value) {
          case 1: return PROTOBUF_BINARY_FORMAT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageEncoding>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageEncoding>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageEncoding>() {
              public MessageEncoding findValueByNumber(int number) {
                return MessageEncoding.valueOf(number);
              }
            };

      private final int value;

      private MessageEncoding(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.ChannelMessageEncoding.MessageEncoding)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.ChannelMessageEncoding}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding, Builder>
        implements com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncodingOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding build() {
        com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding buildPartial() {
        com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding result = new com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding(this);
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding other) {
        if (other == com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.getDefaultInstance()) return this;
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.ChannelMessageEncoding)
    }

    static {
      defaultInstance = new ChannelMessageEncoding(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.ChannelMessageEncoding)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
