// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.google.protos.ipc.invalidation;

public final class Client {
  private Client() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AckHandlePOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;</code>
     */
    boolean hasInvalidation();
    /**
     * <code>optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;</code>
     */
    com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP getInvalidation();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.AckHandleP}
   *
   * <pre>
   * An object that is serialized and given to clients for acknowledgement
   * purposes.
   * </pre>
   */
  public static final class AckHandleP extends
      com.google.protobuf.GeneratedMessageLite
      implements AckHandlePOrBuilder {
    // Use AckHandleP.newBuilder() to construct.
    private AckHandleP(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private AckHandleP(boolean noInit) {}

    private static final AckHandleP defaultInstance;
    public static AckHandleP getDefaultInstance() {
      return defaultInstance;
    }

    public AckHandleP getDefaultInstanceForType() {
      return defaultInstance;
    }

    private AckHandleP(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = invalidation_.toBuilder();
              }
              invalidation_ = input.readMessage(com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(invalidation_);
                invalidation_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<AckHandleP> PARSER =
        new com.google.protobuf.AbstractParser<AckHandleP>() {
      public AckHandleP parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AckHandleP(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AckHandleP> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;
    public static final int INVALIDATION_FIELD_NUMBER = 1;
    private com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP invalidation_;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;</code>
     */
    public boolean hasInvalidation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;</code>
     */
    public com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP getInvalidation() {
      return invalidation_;
    }

    private void initFields() {
      invalidation_ = com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, invalidation_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, invalidation_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Client.AckHandleP prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.AckHandleP}
     *
     * <pre>
     * An object that is serialized and given to clients for acknowledgement
     * purposes.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Client.AckHandleP, Builder>
        implements com.google.protos.ipc.invalidation.Client.AckHandlePOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.Client.AckHandleP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        invalidation_ = com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.Client.AckHandleP getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Client.AckHandleP.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.Client.AckHandleP build() {
        com.google.protos.ipc.invalidation.Client.AckHandleP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.Client.AckHandleP buildPartial() {
        com.google.protos.ipc.invalidation.Client.AckHandleP result = new com.google.protos.ipc.invalidation.Client.AckHandleP(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.invalidation_ = invalidation_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.Client.AckHandleP other) {
        if (other == com.google.protos.ipc.invalidation.Client.AckHandleP.getDefaultInstance()) return this;
        if (other.hasInvalidation()) {
          mergeInvalidation(other.getInvalidation());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.Client.AckHandleP parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.Client.AckHandleP) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;
      private com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP invalidation_ = com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.getDefaultInstance();
      /**
       * <code>optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;</code>
       */
      public boolean hasInvalidation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;</code>
       */
      public com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP getInvalidation() {
        return invalidation_;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;</code>
       */
      public Builder setInvalidation(com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP value) {
        if (value == null) {
          throw new NullPointerException();
        }
        invalidation_ = value;

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;</code>
       */
      public Builder setInvalidation(
          com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.Builder builderForValue) {
        invalidation_ = builderForValue.build();

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;</code>
       */
      public Builder mergeInvalidation(com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            invalidation_ != com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.getDefaultInstance()) {
          invalidation_ =
            com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.newBuilder(invalidation_).mergeFrom(value).buildPartial();
        } else {
          invalidation_ = value;
        }

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;</code>
       */
      public Builder clearInvalidation() {
        invalidation_ = com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.AckHandleP)
    }

    static {
      defaultInstance = new AckHandleP(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.AckHandleP)
  }

  public interface PersistentTiclStateOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional bytes client_token = 1;
    /**
     * <code>optional bytes client_token = 1;</code>
     *
     * <pre>
     * Last token received from the server (required).
     * </pre>
     */
    boolean hasClientToken();
    /**
     * <code>optional bytes client_token = 1;</code>
     *
     * <pre>
     * Last token received from the server (required).
     * </pre>
     */
    com.google.protobuf.ByteString getClientToken();

    // optional int64 last_message_send_time_ms = 2 [default = 0];
    /**
     * <code>optional int64 last_message_send_time_ms = 2 [default = 0];</code>
     *
     * <pre>
     * Last time a message was sent to the server (optional). Must be a value
     * returned by the clock in the Ticl system resources.
     * </pre>
     */
    boolean hasLastMessageSendTimeMs();
    /**
     * <code>optional int64 last_message_send_time_ms = 2 [default = 0];</code>
     *
     * <pre>
     * Last time a message was sent to the server (optional). Must be a value
     * returned by the clock in the Ticl system resources.
     * </pre>
     */
    long getLastMessageSendTimeMs();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.PersistentTiclState}
   *
   * <pre>
   * The state persisted at a client so that it can be used after a reboot.
   * </pre>
   */
  public static final class PersistentTiclState extends
      com.google.protobuf.GeneratedMessageLite
      implements PersistentTiclStateOrBuilder {
    // Use PersistentTiclState.newBuilder() to construct.
    private PersistentTiclState(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private PersistentTiclState(boolean noInit) {}

    private static final PersistentTiclState defaultInstance;
    public static PersistentTiclState getDefaultInstance() {
      return defaultInstance;
    }

    public PersistentTiclState getDefaultInstanceForType() {
      return defaultInstance;
    }

    private PersistentTiclState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              clientToken_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lastMessageSendTimeMs_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<PersistentTiclState> PARSER =
        new com.google.protobuf.AbstractParser<PersistentTiclState>() {
      public PersistentTiclState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersistentTiclState(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PersistentTiclState> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes client_token = 1;
    public static final int CLIENT_TOKEN_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString clientToken_;
    /**
     * <code>optional bytes client_token = 1;</code>
     *
     * <pre>
     * Last token received from the server (required).
     * </pre>
     */
    public boolean hasClientToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes client_token = 1;</code>
     *
     * <pre>
     * Last token received from the server (required).
     * </pre>
     */
    public com.google.protobuf.ByteString getClientToken() {
      return clientToken_;
    }

    // optional int64 last_message_send_time_ms = 2 [default = 0];
    public static final int LAST_MESSAGE_SEND_TIME_MS_FIELD_NUMBER = 2;
    private long lastMessageSendTimeMs_;
    /**
     * <code>optional int64 last_message_send_time_ms = 2 [default = 0];</code>
     *
     * <pre>
     * Last time a message was sent to the server (optional). Must be a value
     * returned by the clock in the Ticl system resources.
     * </pre>
     */
    public boolean hasLastMessageSendTimeMs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 last_message_send_time_ms = 2 [default = 0];</code>
     *
     * <pre>
     * Last time a message was sent to the server (optional). Must be a value
     * returned by the clock in the Ticl system resources.
     * </pre>
     */
    public long getLastMessageSendTimeMs() {
      return lastMessageSendTimeMs_;
    }

    private void initFields() {
      clientToken_ = com.google.protobuf.ByteString.EMPTY;
      lastMessageSendTimeMs_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, clientToken_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, lastMessageSendTimeMs_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, clientToken_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, lastMessageSendTimeMs_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Client.PersistentTiclState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.PersistentTiclState}
     *
     * <pre>
     * The state persisted at a client so that it can be used after a reboot.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Client.PersistentTiclState, Builder>
        implements com.google.protos.ipc.invalidation.Client.PersistentTiclStateOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.Client.PersistentTiclState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clientToken_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        lastMessageSendTimeMs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.Client.PersistentTiclState getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Client.PersistentTiclState.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.Client.PersistentTiclState build() {
        com.google.protos.ipc.invalidation.Client.PersistentTiclState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.Client.PersistentTiclState buildPartial() {
        com.google.protos.ipc.invalidation.Client.PersistentTiclState result = new com.google.protos.ipc.invalidation.Client.PersistentTiclState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientToken_ = clientToken_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lastMessageSendTimeMs_ = lastMessageSendTimeMs_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.Client.PersistentTiclState other) {
        if (other == com.google.protos.ipc.invalidation.Client.PersistentTiclState.getDefaultInstance()) return this;
        if (other.hasClientToken()) {
          setClientToken(other.getClientToken());
        }
        if (other.hasLastMessageSendTimeMs()) {
          setLastMessageSendTimeMs(other.getLastMessageSendTimeMs());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.Client.PersistentTiclState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.Client.PersistentTiclState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes client_token = 1;
      private com.google.protobuf.ByteString clientToken_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes client_token = 1;</code>
       *
       * <pre>
       * Last token received from the server (required).
       * </pre>
       */
      public boolean hasClientToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes client_token = 1;</code>
       *
       * <pre>
       * Last token received from the server (required).
       * </pre>
       */
      public com.google.protobuf.ByteString getClientToken() {
        return clientToken_;
      }
      /**
       * <code>optional bytes client_token = 1;</code>
       *
       * <pre>
       * Last token received from the server (required).
       * </pre>
       */
      public Builder setClientToken(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientToken_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes client_token = 1;</code>
       *
       * <pre>
       * Last token received from the server (required).
       * </pre>
       */
      public Builder clearClientToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientToken_ = getDefaultInstance().getClientToken();
        
        return this;
      }

      // optional int64 last_message_send_time_ms = 2 [default = 0];
      private long lastMessageSendTimeMs_ ;
      /**
       * <code>optional int64 last_message_send_time_ms = 2 [default = 0];</code>
       *
       * <pre>
       * Last time a message was sent to the server (optional). Must be a value
       * returned by the clock in the Ticl system resources.
       * </pre>
       */
      public boolean hasLastMessageSendTimeMs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 last_message_send_time_ms = 2 [default = 0];</code>
       *
       * <pre>
       * Last time a message was sent to the server (optional). Must be a value
       * returned by the clock in the Ticl system resources.
       * </pre>
       */
      public long getLastMessageSendTimeMs() {
        return lastMessageSendTimeMs_;
      }
      /**
       * <code>optional int64 last_message_send_time_ms = 2 [default = 0];</code>
       *
       * <pre>
       * Last time a message was sent to the server (optional). Must be a value
       * returned by the clock in the Ticl system resources.
       * </pre>
       */
      public Builder setLastMessageSendTimeMs(long value) {
        bitField0_ |= 0x00000002;
        lastMessageSendTimeMs_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 last_message_send_time_ms = 2 [default = 0];</code>
       *
       * <pre>
       * Last time a message was sent to the server (optional). Must be a value
       * returned by the clock in the Ticl system resources.
       * </pre>
       */
      public Builder clearLastMessageSendTimeMs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastMessageSendTimeMs_ = 0L;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.PersistentTiclState)
    }

    static {
      defaultInstance = new PersistentTiclState(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.PersistentTiclState)
  }

  public interface PersistentStateBlobOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;</code>
     *
     * <pre>
     * The (important parts of the) Ticl's internal state.
     * </pre>
     */
    boolean hasTiclState();
    /**
     * <code>optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;</code>
     *
     * <pre>
     * The (important parts of the) Ticl's internal state.
     * </pre>
     */
    com.google.protos.ipc.invalidation.Client.PersistentTiclState getTiclState();

    // optional bytes authentication_code = 2;
    /**
     * <code>optional bytes authentication_code = 2;</code>
     *
     * <pre>
     * Implementation-specific message authentication code for the Ticl state.
     * </pre>
     */
    boolean hasAuthenticationCode();
    /**
     * <code>optional bytes authentication_code = 2;</code>
     *
     * <pre>
     * Implementation-specific message authentication code for the Ticl state.
     * </pre>
     */
    com.google.protobuf.ByteString getAuthenticationCode();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.PersistentStateBlob}
   *
   * <pre>
   * An envelope containing a Ticl's internal state, along with a digest of the
   * serialized representation of this state, to ensure its integrity across
   * reads and writes to persistent storage.
   * </pre>
   */
  public static final class PersistentStateBlob extends
      com.google.protobuf.GeneratedMessageLite
      implements PersistentStateBlobOrBuilder {
    // Use PersistentStateBlob.newBuilder() to construct.
    private PersistentStateBlob(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private PersistentStateBlob(boolean noInit) {}

    private static final PersistentStateBlob defaultInstance;
    public static PersistentStateBlob getDefaultInstance() {
      return defaultInstance;
    }

    public PersistentStateBlob getDefaultInstanceForType() {
      return defaultInstance;
    }

    private PersistentStateBlob(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protos.ipc.invalidation.Client.PersistentTiclState.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = ticlState_.toBuilder();
              }
              ticlState_ = input.readMessage(com.google.protos.ipc.invalidation.Client.PersistentTiclState.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ticlState_);
                ticlState_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              authenticationCode_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<PersistentStateBlob> PARSER =
        new com.google.protobuf.AbstractParser<PersistentStateBlob>() {
      public PersistentStateBlob parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersistentStateBlob(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PersistentStateBlob> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;
    public static final int TICL_STATE_FIELD_NUMBER = 1;
    private com.google.protos.ipc.invalidation.Client.PersistentTiclState ticlState_;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;</code>
     *
     * <pre>
     * The (important parts of the) Ticl's internal state.
     * </pre>
     */
    public boolean hasTiclState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;</code>
     *
     * <pre>
     * The (important parts of the) Ticl's internal state.
     * </pre>
     */
    public com.google.protos.ipc.invalidation.Client.PersistentTiclState getTiclState() {
      return ticlState_;
    }

    // optional bytes authentication_code = 2;
    public static final int AUTHENTICATION_CODE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString authenticationCode_;
    /**
     * <code>optional bytes authentication_code = 2;</code>
     *
     * <pre>
     * Implementation-specific message authentication code for the Ticl state.
     * </pre>
     */
    public boolean hasAuthenticationCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes authentication_code = 2;</code>
     *
     * <pre>
     * Implementation-specific message authentication code for the Ticl state.
     * </pre>
     */
    public com.google.protobuf.ByteString getAuthenticationCode() {
      return authenticationCode_;
    }

    private void initFields() {
      ticlState_ = com.google.protos.ipc.invalidation.Client.PersistentTiclState.getDefaultInstance();
      authenticationCode_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, ticlState_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, authenticationCode_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, ticlState_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, authenticationCode_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Client.PersistentStateBlob prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.PersistentStateBlob}
     *
     * <pre>
     * An envelope containing a Ticl's internal state, along with a digest of the
     * serialized representation of this state, to ensure its integrity across
     * reads and writes to persistent storage.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Client.PersistentStateBlob, Builder>
        implements com.google.protos.ipc.invalidation.Client.PersistentStateBlobOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.Client.PersistentStateBlob.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ticlState_ = com.google.protos.ipc.invalidation.Client.PersistentTiclState.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        authenticationCode_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.Client.PersistentStateBlob getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Client.PersistentStateBlob.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.Client.PersistentStateBlob build() {
        com.google.protos.ipc.invalidation.Client.PersistentStateBlob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.Client.PersistentStateBlob buildPartial() {
        com.google.protos.ipc.invalidation.Client.PersistentStateBlob result = new com.google.protos.ipc.invalidation.Client.PersistentStateBlob(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ticlState_ = ticlState_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.authenticationCode_ = authenticationCode_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.Client.PersistentStateBlob other) {
        if (other == com.google.protos.ipc.invalidation.Client.PersistentStateBlob.getDefaultInstance()) return this;
        if (other.hasTiclState()) {
          mergeTiclState(other.getTiclState());
        }
        if (other.hasAuthenticationCode()) {
          setAuthenticationCode(other.getAuthenticationCode());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.Client.PersistentStateBlob parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.Client.PersistentStateBlob) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;
      private com.google.protos.ipc.invalidation.Client.PersistentTiclState ticlState_ = com.google.protos.ipc.invalidation.Client.PersistentTiclState.getDefaultInstance();
      /**
       * <code>optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;</code>
       *
       * <pre>
       * The (important parts of the) Ticl's internal state.
       * </pre>
       */
      public boolean hasTiclState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;</code>
       *
       * <pre>
       * The (important parts of the) Ticl's internal state.
       * </pre>
       */
      public com.google.protos.ipc.invalidation.Client.PersistentTiclState getTiclState() {
        return ticlState_;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;</code>
       *
       * <pre>
       * The (important parts of the) Ticl's internal state.
       * </pre>
       */
      public Builder setTiclState(com.google.protos.ipc.invalidation.Client.PersistentTiclState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ticlState_ = value;

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;</code>
       *
       * <pre>
       * The (important parts of the) Ticl's internal state.
       * </pre>
       */
      public Builder setTiclState(
          com.google.protos.ipc.invalidation.Client.PersistentTiclState.Builder builderForValue) {
        ticlState_ = builderForValue.build();

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;</code>
       *
       * <pre>
       * The (important parts of the) Ticl's internal state.
       * </pre>
       */
      public Builder mergeTiclState(com.google.protos.ipc.invalidation.Client.PersistentTiclState value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            ticlState_ != com.google.protos.ipc.invalidation.Client.PersistentTiclState.getDefaultInstance()) {
          ticlState_ =
            com.google.protos.ipc.invalidation.Client.PersistentTiclState.newBuilder(ticlState_).mergeFrom(value).buildPartial();
        } else {
          ticlState_ = value;
        }

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;</code>
       *
       * <pre>
       * The (important parts of the) Ticl's internal state.
       * </pre>
       */
      public Builder clearTiclState() {
        ticlState_ = com.google.protos.ipc.invalidation.Client.PersistentTiclState.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      // optional bytes authentication_code = 2;
      private com.google.protobuf.ByteString authenticationCode_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes authentication_code = 2;</code>
       *
       * <pre>
       * Implementation-specific message authentication code for the Ticl state.
       * </pre>
       */
      public boolean hasAuthenticationCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes authentication_code = 2;</code>
       *
       * <pre>
       * Implementation-specific message authentication code for the Ticl state.
       * </pre>
       */
      public com.google.protobuf.ByteString getAuthenticationCode() {
        return authenticationCode_;
      }
      /**
       * <code>optional bytes authentication_code = 2;</code>
       *
       * <pre>
       * Implementation-specific message authentication code for the Ticl state.
       * </pre>
       */
      public Builder setAuthenticationCode(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        authenticationCode_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes authentication_code = 2;</code>
       *
       * <pre>
       * Implementation-specific message authentication code for the Ticl state.
       * </pre>
       */
      public Builder clearAuthenticationCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        authenticationCode_ = getDefaultInstance().getAuthenticationCode();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.PersistentStateBlob)
    }

    static {
      defaultInstance = new PersistentStateBlob(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.PersistentStateBlob)
  }

  public interface RunStatePOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional .com.google.protos.ipc.invalidation.RunStateP.State state = 1;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.RunStateP.State state = 1;</code>
     */
    boolean hasState();
    /**
     * <code>optional .com.google.protos.ipc.invalidation.RunStateP.State state = 1;</code>
     */
    com.google.protos.ipc.invalidation.Client.RunStateP.State getState();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.RunStateP}
   *
   * <pre>
   * State of a Ticl RunState.
   * </pre>
   */
  public static final class RunStateP extends
      com.google.protobuf.GeneratedMessageLite
      implements RunStatePOrBuilder {
    // Use RunStateP.newBuilder() to construct.
    private RunStateP(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private RunStateP(boolean noInit) {}

    private static final RunStateP defaultInstance;
    public static RunStateP getDefaultInstance() {
      return defaultInstance;
    }

    public RunStateP getDefaultInstanceForType() {
      return defaultInstance;
    }

    private RunStateP(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.protos.ipc.invalidation.Client.RunStateP.State value = com.google.protos.ipc.invalidation.Client.RunStateP.State.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                state_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<RunStateP> PARSER =
        new com.google.protobuf.AbstractParser<RunStateP>() {
      public RunStateP parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RunStateP(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RunStateP> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.google.protos.ipc.invalidation.RunStateP.State}
     */
    public enum State
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>NOT_STARTED = 1;</code>
       */
      NOT_STARTED(0, 1),
      /**
       * <code>STARTED = 2;</code>
       */
      STARTED(1, 2),
      /**
       * <code>STOPPED = 3;</code>
       */
      STOPPED(2, 3),
      ;

      /**
       * <code>NOT_STARTED = 1;</code>
       */
      public static final int NOT_STARTED_VALUE = 1;
      /**
       * <code>STARTED = 2;</code>
       */
      public static final int STARTED_VALUE = 2;
      /**
       * <code>STOPPED = 3;</code>
       */
      public static final int STOPPED_VALUE = 3;


      public final int getNumber() { return value; }

      public static State valueOf(int value) {
        switch (value) {
          case 1: return NOT_STARTED;
          case 2: return STARTED;
          case 3: return STOPPED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<State>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.valueOf(number);
              }
            };

      private final int value;

      private State(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.RunStateP.State)
    }

    private int bitField0_;
    // optional .com.google.protos.ipc.invalidation.RunStateP.State state = 1;
    public static final int STATE_FIELD_NUMBER = 1;
    private com.google.protos.ipc.invalidation.Client.RunStateP.State state_;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.RunStateP.State state = 1;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.protos.ipc.invalidation.RunStateP.State state = 1;</code>
     */
    public com.google.protos.ipc.invalidation.Client.RunStateP.State getState() {
      return state_;
    }

    private void initFields() {
      state_ = com.google.protos.ipc.invalidation.Client.RunStateP.State.NOT_STARTED;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, state_.getNumber());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_.getNumber());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.Client.RunStateP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Client.RunStateP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.RunStateP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Client.RunStateP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.RunStateP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.RunStateP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.RunStateP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.RunStateP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.RunStateP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.RunStateP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Client.RunStateP prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.RunStateP}
     *
     * <pre>
     * State of a Ticl RunState.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Client.RunStateP, Builder>
        implements com.google.protos.ipc.invalidation.Client.RunStatePOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.Client.RunStateP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        state_ = com.google.protos.ipc.invalidation.Client.RunStateP.State.NOT_STARTED;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.Client.RunStateP getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Client.RunStateP.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.Client.RunStateP build() {
        com.google.protos.ipc.invalidation.Client.RunStateP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.Client.RunStateP buildPartial() {
        com.google.protos.ipc.invalidation.Client.RunStateP result = new com.google.protos.ipc.invalidation.Client.RunStateP(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.Client.RunStateP other) {
        if (other == com.google.protos.ipc.invalidation.Client.RunStateP.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.Client.RunStateP parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.Client.RunStateP) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.google.protos.ipc.invalidation.RunStateP.State state = 1;
      private com.google.protos.ipc.invalidation.Client.RunStateP.State state_ = com.google.protos.ipc.invalidation.Client.RunStateP.State.NOT_STARTED;
      /**
       * <code>optional .com.google.protos.ipc.invalidation.RunStateP.State state = 1;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.RunStateP.State state = 1;</code>
       */
      public com.google.protos.ipc.invalidation.Client.RunStateP.State getState() {
        return state_;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.RunStateP.State state = 1;</code>
       */
      public Builder setState(com.google.protos.ipc.invalidation.Client.RunStateP.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        state_ = value;
        
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.RunStateP.State state = 1;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = com.google.protos.ipc.invalidation.Client.RunStateP.State.NOT_STARTED;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.RunStateP)
    }

    static {
      defaultInstance = new RunStateP(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.RunStateP)
  }

  public interface ExponentialBackoffStateOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional int32 current_max_delay = 1;
    /**
     * <code>optional int32 current_max_delay = 1;</code>
     */
    boolean hasCurrentMaxDelay();
    /**
     * <code>optional int32 current_max_delay = 1;</code>
     */
    int getCurrentMaxDelay();

    // optional bool in_retry_mode = 2;
    /**
     * <code>optional bool in_retry_mode = 2;</code>
     */
    boolean hasInRetryMode();
    /**
     * <code>optional bool in_retry_mode = 2;</code>
     */
    boolean getInRetryMode();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.ExponentialBackoffState}
   *
   * <pre>
   * Fields in this message correspond directly to fields in
   * ExponentialBackoffDelayGenerator.
   * </pre>
   */
  public static final class ExponentialBackoffState extends
      com.google.protobuf.GeneratedMessageLite
      implements ExponentialBackoffStateOrBuilder {
    // Use ExponentialBackoffState.newBuilder() to construct.
    private ExponentialBackoffState(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private ExponentialBackoffState(boolean noInit) {}

    private static final ExponentialBackoffState defaultInstance;
    public static ExponentialBackoffState getDefaultInstance() {
      return defaultInstance;
    }

    public ExponentialBackoffState getDefaultInstanceForType() {
      return defaultInstance;
    }

    private ExponentialBackoffState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              currentMaxDelay_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              inRetryMode_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<ExponentialBackoffState> PARSER =
        new com.google.protobuf.AbstractParser<ExponentialBackoffState>() {
      public ExponentialBackoffState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExponentialBackoffState(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExponentialBackoffState> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 current_max_delay = 1;
    public static final int CURRENT_MAX_DELAY_FIELD_NUMBER = 1;
    private int currentMaxDelay_;
    /**
     * <code>optional int32 current_max_delay = 1;</code>
     */
    public boolean hasCurrentMaxDelay() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 current_max_delay = 1;</code>
     */
    public int getCurrentMaxDelay() {
      return currentMaxDelay_;
    }

    // optional bool in_retry_mode = 2;
    public static final int IN_RETRY_MODE_FIELD_NUMBER = 2;
    private boolean inRetryMode_;
    /**
     * <code>optional bool in_retry_mode = 2;</code>
     */
    public boolean hasInRetryMode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool in_retry_mode = 2;</code>
     */
    public boolean getInRetryMode() {
      return inRetryMode_;
    }

    private void initFields() {
      currentMaxDelay_ = 0;
      inRetryMode_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, currentMaxDelay_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, inRetryMode_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, currentMaxDelay_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, inRetryMode_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.Client.ExponentialBackoffState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Client.ExponentialBackoffState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.ExponentialBackoffState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Client.ExponentialBackoffState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.ExponentialBackoffState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.ExponentialBackoffState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.ExponentialBackoffState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.ExponentialBackoffState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Client.ExponentialBackoffState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Client.ExponentialBackoffState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Client.ExponentialBackoffState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.ExponentialBackoffState}
     *
     * <pre>
     * Fields in this message correspond directly to fields in
     * ExponentialBackoffDelayGenerator.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Client.ExponentialBackoffState, Builder>
        implements com.google.protos.ipc.invalidation.Client.ExponentialBackoffStateOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.Client.ExponentialBackoffState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        currentMaxDelay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        inRetryMode_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.Client.ExponentialBackoffState getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Client.ExponentialBackoffState.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.Client.ExponentialBackoffState build() {
        com.google.protos.ipc.invalidation.Client.ExponentialBackoffState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.Client.ExponentialBackoffState buildPartial() {
        com.google.protos.ipc.invalidation.Client.ExponentialBackoffState result = new com.google.protos.ipc.invalidation.Client.ExponentialBackoffState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.currentMaxDelay_ = currentMaxDelay_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.inRetryMode_ = inRetryMode_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.Client.ExponentialBackoffState other) {
        if (other == com.google.protos.ipc.invalidation.Client.ExponentialBackoffState.getDefaultInstance()) return this;
        if (other.hasCurrentMaxDelay()) {
          setCurrentMaxDelay(other.getCurrentMaxDelay());
        }
        if (other.hasInRetryMode()) {
          setInRetryMode(other.getInRetryMode());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.Client.ExponentialBackoffState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.Client.ExponentialBackoffState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 current_max_delay = 1;
      private int currentMaxDelay_ ;
      /**
       * <code>optional int32 current_max_delay = 1;</code>
       */
      public boolean hasCurrentMaxDelay() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 current_max_delay = 1;</code>
       */
      public int getCurrentMaxDelay() {
        return currentMaxDelay_;
      }
      /**
       * <code>optional int32 current_max_delay = 1;</code>
       */
      public Builder setCurrentMaxDelay(int value) {
        bitField0_ |= 0x00000001;
        currentMaxDelay_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 current_max_delay = 1;</code>
       */
      public Builder clearCurrentMaxDelay() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currentMaxDelay_ = 0;
        
        return this;
      }

      // optional bool in_retry_mode = 2;
      private boolean inRetryMode_ ;
      /**
       * <code>optional bool in_retry_mode = 2;</code>
       */
      public boolean hasInRetryMode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool in_retry_mode = 2;</code>
       */
      public boolean getInRetryMode() {
        return inRetryMode_;
      }
      /**
       * <code>optional bool in_retry_mode = 2;</code>
       */
      public Builder setInRetryMode(boolean value) {
        bitField0_ |= 0x00000002;
        inRetryMode_ = value;
        
        return this;
      }
      /**
       * <code>optional bool in_retry_mode = 2;</code>
       */
      public Builder clearInRetryMode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        inRetryMode_ = false;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.ExponentialBackoffState)
    }

    static {
      defaultInstance = new ExponentialBackoffState(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.ExponentialBackoffState)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
