// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.google.protos.ipc.invalidation;

public final class Types {
  private Types() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ClientTypeOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;</code>
     */
    com.google.protos.ipc.invalidation.Types.ClientType.Type getType();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.ClientType}
   *
   * <pre>
   * The type of client / application.
   * </pre>
   */
  public static final class ClientType extends
      com.google.protobuf.GeneratedMessageLite
      implements ClientTypeOrBuilder {
    // Use ClientType.newBuilder() to construct.
    private ClientType(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private ClientType(boolean noInit) {}

    private static final ClientType defaultInstance;
    public static ClientType getDefaultInstance() {
      return defaultInstance;
    }

    public ClientType getDefaultInstanceForType() {
      return defaultInstance;
    }

    private ClientType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.protos.ipc.invalidation.Types.ClientType.Type value = com.google.protos.ipc.invalidation.Types.ClientType.Type.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<ClientType> PARSER =
        new com.google.protobuf.AbstractParser<ClientType>() {
      public ClientType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientType(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientType> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.google.protos.ipc.invalidation.ClientType.Type}
     */
    public enum Type
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>INTERNAL = 1;</code>
       */
      INTERNAL(0, 1),
      /**
       * <code>TEST = 2;</code>
       *
       * <pre>
       * Uncontrolled client space for use by anyone for testing.
       * </pre>
       */
      TEST(1, 2),
      /**
       * <code>DEMO = 4;</code>
       *
       * <pre>
       * A demo client type that can be used for testing.
       * </pre>
       */
      DEMO(2, 4),
      /**
       * <code>CHROME_SYNC = 1004;</code>
       *
       * <pre>
       * Numbers below 1000 are reserved for internal use.
       * </pre>
       */
      CHROME_SYNC(3, 1004),
      /**
       * <code>CHROME_SYNC_ANDROID = 1018;</code>
       */
      CHROME_SYNC_ANDROID(4, 1018),
      /**
       * <code>CHROME_SYNC_IOS = 1038;</code>
       */
      CHROME_SYNC_IOS(5, 1038),
      ;

      /**
       * <code>INTERNAL = 1;</code>
       */
      public static final int INTERNAL_VALUE = 1;
      /**
       * <code>TEST = 2;</code>
       *
       * <pre>
       * Uncontrolled client space for use by anyone for testing.
       * </pre>
       */
      public static final int TEST_VALUE = 2;
      /**
       * <code>DEMO = 4;</code>
       *
       * <pre>
       * A demo client type that can be used for testing.
       * </pre>
       */
      public static final int DEMO_VALUE = 4;
      /**
       * <code>CHROME_SYNC = 1004;</code>
       *
       * <pre>
       * Numbers below 1000 are reserved for internal use.
       * </pre>
       */
      public static final int CHROME_SYNC_VALUE = 1004;
      /**
       * <code>CHROME_SYNC_ANDROID = 1018;</code>
       */
      public static final int CHROME_SYNC_ANDROID_VALUE = 1018;
      /**
       * <code>CHROME_SYNC_IOS = 1038;</code>
       */
      public static final int CHROME_SYNC_IOS_VALUE = 1038;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return INTERNAL;
          case 2: return TEST;
          case 4: return DEMO;
          case 1004: return CHROME_SYNC;
          case 1018: return CHROME_SYNC_ANDROID;
          case 1038: return CHROME_SYNC_IOS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      private final int value;

      private Type(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.ClientType.Type)
    }

    private int bitField0_;
    // optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.google.protos.ipc.invalidation.Types.ClientType.Type type_;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;</code>
     */
    public com.google.protos.ipc.invalidation.Types.ClientType.Type getType() {
      return type_;
    }

    private void initFields() {
      type_ = com.google.protos.ipc.invalidation.Types.ClientType.Type.INTERNAL;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Types.ClientType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.ClientType}
     *
     * <pre>
     * The type of client / application.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Types.ClientType, Builder>
        implements com.google.protos.ipc.invalidation.Types.ClientTypeOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.Types.ClientType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.google.protos.ipc.invalidation.Types.ClientType.Type.INTERNAL;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.Types.ClientType getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Types.ClientType.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.Types.ClientType build() {
        com.google.protos.ipc.invalidation.Types.ClientType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.Types.ClientType buildPartial() {
        com.google.protos.ipc.invalidation.Types.ClientType result = new com.google.protos.ipc.invalidation.Types.ClientType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.Types.ClientType other) {
        if (other == com.google.protos.ipc.invalidation.Types.ClientType.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.Types.ClientType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.Types.ClientType) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;
      private com.google.protos.ipc.invalidation.Types.ClientType.Type type_ = com.google.protos.ipc.invalidation.Types.ClientType.Type.INTERNAL;
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;</code>
       */
      public com.google.protos.ipc.invalidation.Types.ClientType.Type getType() {
        return type_;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;</code>
       */
      public Builder setType(com.google.protos.ipc.invalidation.Types.ClientType.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.google.protos.ipc.invalidation.Types.ClientType.Type.INTERNAL;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.ClientType)
    }

    static {
      defaultInstance = new ClientType(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.ClientType)
  }

  public interface ObjectSourceOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;</code>
     */
    com.google.protos.ipc.invalidation.Types.ObjectSource.Type getType();
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.ObjectSource}
   *
   * <pre>
   * The property that hosts the object.
   * </pre>
   */
  public static final class ObjectSource extends
      com.google.protobuf.GeneratedMessageLite
      implements ObjectSourceOrBuilder {
    // Use ObjectSource.newBuilder() to construct.
    private ObjectSource(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private ObjectSource(boolean noInit) {}

    private static final ObjectSource defaultInstance;
    public static ObjectSource getDefaultInstance() {
      return defaultInstance;
    }

    public ObjectSource getDefaultInstanceForType() {
      return defaultInstance;
    }

    private ObjectSource(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.protos.ipc.invalidation.Types.ObjectSource.Type value = com.google.protos.ipc.invalidation.Types.ObjectSource.Type.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<ObjectSource> PARSER =
        new com.google.protobuf.AbstractParser<ObjectSource>() {
      public ObjectSource parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ObjectSource(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ObjectSource> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.google.protos.ipc.invalidation.ObjectSource.Type}
     *
     * <pre>
     *
     * NOTE: This enum MUST be kept in sync with ObjectIdP.Source in
     * internal.proto.
     * </pre>
     */
    public enum Type
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>INTERNAL = 1;</code>
       */
      INTERNAL(0, 1),
      /**
       * <code>TEST = 2;</code>
       *
       * <pre>
       * Uncontrolled object space for use by anyone for testing.
       * </pre>
       */
      TEST(1, 2),
      /**
       * <code>DEMO = 4;</code>
       *
       * <pre>
       * A demo object source that can be used for testing.
       * </pre>
       */
      DEMO(2, 4),
      /**
       * <code>CHROME_SYNC = 1004;</code>
       *
       * <pre>
       * Numbers below 1000 are reserved for internal use.
       * </pre>
       */
      CHROME_SYNC(3, 1004),
      /**
       * <code>COSMO_CHANGELOG = 1014;</code>
       */
      COSMO_CHANGELOG(4, 1014),
      /**
       * <code>CHROME_COMPONENTS = 1025;</code>
       */
      CHROME_COMPONENTS(5, 1025),
      /**
       * <code>CHROME_PUSH_MESSAGING = 1030;</code>
       */
      CHROME_PUSH_MESSAGING(6, 1030),
      ;

      /**
       * <code>INTERNAL = 1;</code>
       */
      public static final int INTERNAL_VALUE = 1;
      /**
       * <code>TEST = 2;</code>
       *
       * <pre>
       * Uncontrolled object space for use by anyone for testing.
       * </pre>
       */
      public static final int TEST_VALUE = 2;
      /**
       * <code>DEMO = 4;</code>
       *
       * <pre>
       * A demo object source that can be used for testing.
       * </pre>
       */
      public static final int DEMO_VALUE = 4;
      /**
       * <code>CHROME_SYNC = 1004;</code>
       *
       * <pre>
       * Numbers below 1000 are reserved for internal use.
       * </pre>
       */
      public static final int CHROME_SYNC_VALUE = 1004;
      /**
       * <code>COSMO_CHANGELOG = 1014;</code>
       */
      public static final int COSMO_CHANGELOG_VALUE = 1014;
      /**
       * <code>CHROME_COMPONENTS = 1025;</code>
       */
      public static final int CHROME_COMPONENTS_VALUE = 1025;
      /**
       * <code>CHROME_PUSH_MESSAGING = 1030;</code>
       */
      public static final int CHROME_PUSH_MESSAGING_VALUE = 1030;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return INTERNAL;
          case 2: return TEST;
          case 4: return DEMO;
          case 1004: return CHROME_SYNC;
          case 1014: return COSMO_CHANGELOG;
          case 1025: return CHROME_COMPONENTS;
          case 1030: return CHROME_PUSH_MESSAGING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      private final int value;

      private Type(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.ObjectSource.Type)
    }

    private int bitField0_;
    // optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.google.protos.ipc.invalidation.Types.ObjectSource.Type type_;
    /**
     * <code>optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;</code>
     */
    public com.google.protos.ipc.invalidation.Types.ObjectSource.Type getType() {
      return type_;
    }

    private void initFields() {
      type_ = com.google.protos.ipc.invalidation.Types.ObjectSource.Type.INTERNAL;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Types.ObjectSource prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.ObjectSource}
     *
     * <pre>
     * The property that hosts the object.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Types.ObjectSource, Builder>
        implements com.google.protos.ipc.invalidation.Types.ObjectSourceOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.Types.ObjectSource.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.google.protos.ipc.invalidation.Types.ObjectSource.Type.INTERNAL;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.Types.ObjectSource getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Types.ObjectSource.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.Types.ObjectSource build() {
        com.google.protos.ipc.invalidation.Types.ObjectSource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.Types.ObjectSource buildPartial() {
        com.google.protos.ipc.invalidation.Types.ObjectSource result = new com.google.protos.ipc.invalidation.Types.ObjectSource(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.Types.ObjectSource other) {
        if (other == com.google.protos.ipc.invalidation.Types.ObjectSource.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.Types.ObjectSource parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.Types.ObjectSource) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;
      private com.google.protos.ipc.invalidation.Types.ObjectSource.Type type_ = com.google.protos.ipc.invalidation.Types.ObjectSource.Type.INTERNAL;
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;</code>
       */
      public com.google.protos.ipc.invalidation.Types.ObjectSource.Type getType() {
        return type_;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;</code>
       */
      public Builder setType(com.google.protos.ipc.invalidation.Types.ObjectSource.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        
        return this;
      }
      /**
       * <code>optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.google.protos.ipc.invalidation.Types.ObjectSource.Type.INTERNAL;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.ObjectSource)
    }

    static {
      defaultInstance = new ObjectSource(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.ObjectSource)
  }

  public interface ConstantsOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code com.google.protos.ipc.invalidation.Constants}
   *
   * <pre>
   * A dummy message to enclose various enum constant declarations.
   * </pre>
   */
  public static final class Constants extends
      com.google.protobuf.GeneratedMessageLite
      implements ConstantsOrBuilder {
    // Use Constants.newBuilder() to construct.
    private Constants(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Constants(boolean noInit) {}

    private static final Constants defaultInstance;
    public static Constants getDefaultInstance() {
      return defaultInstance;
    }

    public Constants getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Constants(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Constants> PARSER =
        new com.google.protobuf.AbstractParser<Constants>() {
      public Constants parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Constants(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Constants> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.google.protos.ipc.invalidation.Constants.ObjectVersion}
     *
     * <pre>
     * Constants related to object versions.
     * </pre>
     */
    public enum ObjectVersion
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>UNKNOWN = 0;</code>
       *
       * <pre>
       * Version number used to indicate that an object's version is unknown.
       * </pre>
       */
      UNKNOWN(0, 0),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       *
       * <pre>
       * Version number used to indicate that an object's version is unknown.
       * </pre>
       */
      public static final int UNKNOWN_VALUE = 0;


      public final int getNumber() { return value; }

      public static ObjectVersion valueOf(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ObjectVersion>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ObjectVersion>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ObjectVersion>() {
              public ObjectVersion findValueByNumber(int number) {
                return ObjectVersion.valueOf(number);
              }
            };

      private final int value;

      private ObjectVersion(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.Constants.ObjectVersion)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Types.Constants prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.protos.ipc.invalidation.Constants}
     *
     * <pre>
     * A dummy message to enclose various enum constant declarations.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Types.Constants, Builder>
        implements com.google.protos.ipc.invalidation.Types.ConstantsOrBuilder {
      // Construct using com.google.protos.ipc.invalidation.Types.Constants.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protos.ipc.invalidation.Types.Constants getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Types.Constants.getDefaultInstance();
      }

      public com.google.protos.ipc.invalidation.Types.Constants build() {
        com.google.protos.ipc.invalidation.Types.Constants result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protos.ipc.invalidation.Types.Constants buildPartial() {
        com.google.protos.ipc.invalidation.Types.Constants result = new com.google.protos.ipc.invalidation.Types.Constants(this);
        return result;
      }

      public Builder mergeFrom(com.google.protos.ipc.invalidation.Types.Constants other) {
        if (other == com.google.protos.ipc.invalidation.Types.Constants.getDefaultInstance()) return this;
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.ipc.invalidation.Types.Constants parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.ipc.invalidation.Types.Constants) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.Constants)
    }

    static {
      defaultInstance = new Constants(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.Constants)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
